---
title: "Standardisierte Tests in der Mathematik"
format: html

---

# Thematischer Einstieg

Als Vorbereitung werden folgende drei Medien in absteigender Reihenfolge der Wissenschaftlichkeit genannt:

* [@imlig_towards_2018]
* [Prüfungen abschaffen, Video (Jörn Loviscach)](https://phbern365.sharepoint.com/:v:/s/IS1_Z_FachteamMathematik/EXfwrFDtzjNArMaGyWiosRcB22QMC9y1QE48GTob05l-2A?e=th92S0)
* [Standardized Testing, Video (John Oliver)](https://phbern365.sharepoint.com/:v:/s/IS1_Z_FachteamMathematik/EUjsTQSfUqBKqO5O4IHLjGcByhdi_l6QqreFOfjW0uiNrA?e=QdjpoN)
  
---
### Test Ende 9. Klasse

#### International

Ein **internationaler** Vergleich mittels standardisiertem Test erfolgt mittels [PISA](https://www.oecd.org/pisa/publications/pisa-2018-results.htm) bei Lernenden welche das 15. Lebensjahr erreich haben. Das [Country Note - Switzerland](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EcYeJ2XBvdRPp28NTYD9W04BO1QMAOz18YZOlDue41v8SA?e=pwl4Cz) ist eine kurze Zusammenfassung für die Schweiz. Um sich ein Bild der Aufgaben zu machen gibt es [PISA 2012: Veröffentlichte Beispielaufgaben - Mathematik](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/Ee4USkcuFWVFti6wvTDG1BkB6E7C4Y4XN4WX9UKq44GayA?e=GMfeYZ)

#### National

Ein **nationales**, staatliches Projekt bei welchem Lernende der Sekundarstufe regelmässig auf ihre Mathematikleistung geprüft wurden, ist die [Überprüfung der Grundkompetenzen (ÜGK) von 2016](https://www.uegk-schweiz.ch). Deren [ÜGK 2016Schlussbericht](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EUJDu0pLGFFFjiDAmUHQlpsBRv9a3GJ-5AzNuCNfcwFa5Q?e=4l9mvo) ermöglicht einen nationalen Vergleich. Ab 2028 wird dieses Monitoring regelmässig durchgeführt [(vgl. EDK)](https://www.edk.ch/de/die-edk/blog/271023).

#### Kantonal

[Übertritt Sek I - Sek II](https://www.akvb-unterricht.bkd.be.ch/de/start/unterricht/beurteilung-uebertritte/uebertritt-sek-i-sek-ii.html)
  - [BFS - Maturitätsquote](https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/bildungsindikatoren/themen/bildungserfolg/maturitaetsquote.html)

### Test Ende 6. Klasse

#### Kantonal

Auf **kantonaler** Ebene gibt es gewisse Prüfungen, welche ebenfalls als standardisiert bezeichnet werden können. Sie werden jährlich durchgeführt und messen kantonsweit die gleichen Standards.

Die [Übertritt PRIM - Sek I Kontrollprüfungen](https://www.akvb-unterricht.bkd.be.ch/de/start/unterricht/beurteilung-uebertritte/uebertritt-prim-sek-i-kontrollpruefung.html) ist ein solches Beispiel. Das [Monitoring Kontrollprüfungen 2023](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/ETVJKe4XX45GmoWGze8pq6MB4lLQXPt7U9aqCshkvrVUEQ?e=3CJbXt) gibt hier Auskunft über die Resultate.
Der [Referenzrahmen Mathematik](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EXiCoKrAXTlKj5-TaomEti0B2MoqY4YFD-Mn3ScFbtcD5g?e=wsclIZ) gibt dabei eine genauere Auskunft über die erreichenden Kompetenzen Ende 6. Klasse, bzw. welche Kompetenzen von Primarschülern in der 7. Klasse erwartet werden können.

Da es mit dem Lehrplan21 eine gewisse Standardisierung (Homegenisierung) der obligatorischen Schulzeit gibt, sind die Daten des Bundesamts für Statistik auch vergleichbar. 

### Tests der postobligatorischen Schulzeit

#### EMS

Der Eignungstest für das Medizinstudium in der Schweiz (EMS) prüft ebenfalls Mathematikkompetenzen auf Niveau @ztd_unifr_beispielaufgaben_2021


--------------

  - [BFS -  Selektion auf der Sekundarstufe I](https://www.bfs.admin.ch/bfs/de/home/statistiken/wirtschaftliche-soziale-situation-bevoelkerung/gleichstellun-frau-mann/bildung/bildungsstand.assetdetail.24485156.html)

  - [BFS - Löhne nach Kompetenzniveau, Bildung und beruflicher Stellung ](https://www.bfs.admin.ch/bfs/de/home/statistiken/wirtschaftliche-soziale-situation-bevoelkerung/gleichstellung-frau-mann/loehne/kompetenzniveau-bildung-berufliche-stellung.html)
- [Artikel: der Bund](https://www.derbund.ch/die-ungerechtigkeit-ist-in-bern-eher-groesser-als-in-zuerich-325562265525)
- 


Weitere Dokumente:

- [Evaluationen Kanton Bern](https://www.bkd.be.ch/de/start/themen/statistik-bildung-und-kultur/daten-publikationen/evaluationen-bildungsmonitoring.html)
