---
title: "Summative Beurteilung im Mathematikunterricht"
subtitle: "Grundlagen für den Unterricht, Präsenzveranstaltung"
format: html
categories:
  - Summative und prognostische Beurteilung
---

# Organisatorisches

::: {style="text-align: center;"}
[Organisationsblatt](https://phbern365.sharepoint.com/:x:/r/sites/IS1_Z_FachteamMathematik/Freigegebene%20Dokumente/General/Lerngelegenheiten/Summative%20Beurteilung%20im%20Mathematikunterricht/Pr%C3%A4senzkurs_Schreibrechte_Studierende/Organisationsblatt_Summ_Praes.xlsx?d=wf606fa7c49d4435a8505a9f2c621dd67&csf=1&web=1&e=czb7Xz){.knopf target="_blank"}

[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){.knopf .knopf-klein target="_blank"} [Materialraum](https://ilias.phbern.ch/goto_phbern_fold_2177856.html){.knopf .knopf-klein target="_blank"}
:::

| Woche | Thema                                 |                               Slides                               |
|:-----------------:|:------------------|:-----------------:|
|   1   | Constructive Alignment                | [<i class="bi bi-easel3-fill"></i>](woche_01.qmd){target="_blank"} |
|   2   | Lehrplan21                            | [<i class="bi bi-easel3-fill"></i>](woche_02.qmd){target="_blank"} |
|   3   | Mathematische Inhalte und Tätigkeiten | [<i class="bi bi-easel3-fill"></i>](woche_03.qmd){target="_blank"} |
|   7   |                                       |         [<i class="bi bi-easel3-fill"></i>](woche_07.qmd)          |
|   8   |                                       |         [<i class="bi bi-easel3-fill"></i>](woche_08.qmd)          |
|   9   | Algorithmen                           |         [<i class="bi bi-easel3-fill"></i>](woche_09.qmd)          |

: {.striped .hover .table-sm}

# Workload

## Fünf Lernkontrollen

Sie (alle Teilnehmende) erstellen gemeinsam alle fünf Lernkontrollen für eine niveaudurchmischte (Real, Sek und Spez-Sek) **8. Klasse** im deutschsprachigen Teil des Kantons Bern.

Die Lernkontrollen sind unter einer freien Lizenz([CC BY](https://creativecommons.org/licenses/by/4.0/) oder [CC-BY-SA 4.0 Lizenz](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)) didaktisch kohärent und bauen auf wohl ausgewähltem Lehrstoff auf. Die restlichen Rahmenbedingen (Hilfsmittel, Zeit, Aufteilung) legen Sie fest.

Teilen Sie sich gleichmässig auf 5 Themenblöcke auf. Vorschlag:

1.  Zahl und Variable (Arithmetik): Bruchrechnen, Prozentrechnen, SI-System
2.  Grössen, Funktionen, Daten und Zufall (Analysis): Funktionen, lineare Gleichungssysteme, Exponentialfunktionen
3.  Grössen, Funktionen, Daten und Zufall (Stochastik): Wahrscheinlichkeitsrechnen, Kombinatorik
4.  Zahl und Variable (Algebra): Termumformung, Binome, quadratische Gleichungen
5.  Form und Raum (Geometrie): Satz von Thales, Satzgruppe des Pythagoras, Volumen und Oberflächen von geraden Prismen, Pyramiden

Sie dürfen eine andere inhaltlich Einteilungen vorschlagen. Verpflichtend ist der [Lehrplan 21](https://be.lehrplan.ch/). Das [Mathbuch](https://www.mathbuch.info/), sowie [Mathematik vom LMVZ](https://003.lmvz.ch/lehrmittelsites/mathe_sek/de/m2/index.html) können Ihnen nützliche Hilfestellungen geben.
