project:
  type: website
  output-dir: docs

lang: de #Sprache für die Webseite
theme: 
  - styles/phbern_ci.scss # alle Stylesheets
  
date-format: "DD.MM.YYYY" # übliche Daten in der Schweiz

bibliography:     # Liste mite allen Bibliographiedatei
  - bibliographien/bibliographie_richard.bib
  - bibliographien/bib_conrardy_full.bib
csl: bibliographien/apa7.csl          # Zitierstil, wird automatisch angewandt

link-external-newwindow: true  # damit Präsentationen in neuem Tab geöffnet werden.
fig-align: center # Bilder werden zentriert, funktioniert nicht immer



website:  # Menüs für die Webseite
  #cookie-consent: false
   # type: express
  repo-url: https://github.com/PHBern-RConrardy/lerngelegenheiten
  favicon: images/penguin.png
  search: true
  
  navbar:
    logo: "images/penguin.png"
    background: white
    tools:
      - icon: github
        href: https://github.com/PHBern-RConrardy/lerngelegenheiten
      - icon: book-fill
        href: https://www.zotero.org/groups/5512202/literatur_phbern_conrardy

    left:
      - text: Beurteilung
        icon: clipboard-check-fill
        menu: 
          - href: lerngelegenheiten/LG_learning_analytics/LG_learning_analytics.qmd
            text: "Learning Analytics"
            icon: graph-up
          - text: "Grundlagen der Beurteilung"
            href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/LG_grundlagen_der_beurteilung.qmd
            icon: card-checklist
          - href: lerngelegenheiten/LG_summ_digi_datenschutz/LG_datenschutz.qmd
            text: Digitalität und Datenschutz
            icon: shield-fill
          - href: lerngelegenheiten/LG_stand_testverfahren/LG_stand_test.qmd
            text: Chancen und Risiken standardisierter Testverfahren und Leistungsmessung
            icon: file-bar-graph-fill
          - href: lerngelegenheiten/LG_verstehensorientiert_pruefen/LG_math_ki.qmd
            text: "Verstehensorientiert prüfen in Zeiten von KI"
            icon: calculator-fill
            
        
      - text: Mikroplanung
        icon: arrows-angle-contract
        menu: 
          - href: lerngelegenheiten/LG_mikroplanung_math/LG_mikroplanung.qmd
            text: "Mikroplanung Mathematik"
            icon: grid-3x3-gap-fill
          - text: Mediendidaktik
            href: lerngelegenheiten/LG_Mediendidaktik/LG_Mediendidaktik.qmd
            icon: images
      - text: Zus. und Komm.
        icon: chat-text-fill
        menu:
          - text: Digitale Zusammenarbeit und Kommunikation
            href: empty
            icon: share-fill
      - text: Digitalität
        icon: pc-display-horizontal
        menu:
          - text: Medien und Informatik unterrichten
            href: lerngelegenheiten/LG_medien_informatik_unterrichten/LG_medien_informatik_unterrichten.qmd
            icon: easel2-fill
  
  sidebar:
    - title: "Grundlagen der Beurteilung"
      style: "docked"
      background: none
      foreground: none
      collapse-level: 5
      contents:
        - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/LG_grundlagen_der_beurteilung.qmd
          text: Semesterübersicht
        - section: Lernmodule
          contents:
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_01.qmd
            text: Lernmodul 1
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_02.qmd
            text: Lernmodul 2
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_03.qmd
            text: Lernmodul 3
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_04.qmd
            text: Lernmodul 4
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_05.qmd
            text: Lernmodul 5
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_06.qmd
            text: Lernmodul 6
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_07.qmd
            text: Lernmodul 7
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_08.qmd
            text: Lernmodul 8
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_09.qmd
            text: Lernmodul 9
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_10.qmd
            text: Lernmodul 10
          - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Lernmodul_11.qmd
            text: Lernmodul 11
        - href: lerngelegenheiten/LG_ESW_grundlagen_der_beurteilung/Auftrag_Beurteilungskonzept.qmd
          text: Beurteilungskonzept
    - title: "Mikroplanung Mathematik"
      contents:
        - href: lerngelegenheiten/LG_mikroplanung_math/LG_mikroplanung.qmd
          text: Semesterübersicht
        - section: Lernmodule
          contents:
            auto: lerngelegenheiten/LG_mikroplanung_math/Lernmodul*
    - title: "Verstehensorientiert prüfen in Zeiten von KI"
      contents:
        - href: lerngelegenheiten/LG_verstehensorientiert_pruefen/LG_math_ki.qmd
          text: Semesterübersicht
        - section: Lernmodule
          contents:
            - lerngelegenheiten/LG_verstehensorientiert_pruefen/Lernmodul_01.qmd
            - lerngelegenheiten/LG_verstehensorientiert_pruefen/Lernmodul_02.qmd
            - lerngelegenheiten/LG_verstehensorientiert_pruefen/Lernmodul_03.qmd
            - lerngelegenheiten/LG_verstehensorientiert_pruefen/Lernmodul_04.qmd
            - lerngelegenheiten/LG_verstehensorientiert_pruefen/Lernmodul_05.qmd
                    
        - href: lerngelegenheiten/LG_verstehensorientiert_pruefen/aufgabensammlung.qmd
    - title: "Learning Analytics"
      contents:
        - href: lerngelegenheiten/LG_learning_analytics/LG_learning_analytics.qmd
          text: Semesterübersicht
        - section: Lernmodule
          contents:
            - lerngelegenheiten/LG_learning_analytics/Lernmodul_01.qmd
            - lerngelegenheiten/LG_learning_analytics/Lernmodul_02.qmd
            - lerngelegenheiten/LG_learning_analytics/Lernmodul_06.qmd
        - href: lerngelegenheiten/LG_learning_analytics/Auftrag_Learning_Analytics.qmd
          text: Auftrag
        
  page-footer: # Fusszeile
    center: 
      - text: "Impressum"
        href: footer/impressum.qmd
      - text: "Disclaimer"
        href: footer/disclaimer.qmd 
      - text: "Kontakt"
        href: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy  
    left: 
      - text: "PHBern"
        href: https://www.phbern.ch/
    right: 
      - text: <small>Dieses Produkt ist in einem Kontext des Lernens an der PHBern entstanden.</small>
    background: $schwarz1
    foreground: $schwarz4
    
mermaid:
      theme: neutral
filters:
  - reveal-auto-agenda
auto-agenda:
  bullets: numbered
  heading: Inhalt
      
format:
  html: # Einstellungen nur für Webseiten
    toc: true
    toc-expand: true
    toc-location: right
    toc-depth: 2
    license: "CC BY-SA"
    page-layout: article
    title-block-banner: true
    code-line-numbers: true
    fig-align: center
    linkcolor: "#AC0101"
    
      
  revealjs: # Einträge nur für Präsentationen
    toc: false
    slide-number: false
    chalkboard: true
    toc-title: "Inhalt"
    footer: "[PHBern, Institut Sekundarstufe 1,](https://www.phbern.ch/studium/sekundarstufe-i)  Richard Conrardy, Dozent"
    title-slide-attributes: 
      data-background-image: "images/logo cc-by-sa.svg"
      data-background-size: 12%
      data-background-position: 94% 99%
    scrollable: true
    logo: images/penguin.png
    hide-inactive-cursor: true
  
  pdf:
    documentclass: scrartcl
    include-in-header: 
       - "styles/phbern-style.tex"
    mainfont: "Arial"
    fontsize: 10pt
    linkcolor: (3,1.5)
    papersize: a4
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-align: center
    number-sections: true
    number-depth: 3
    
author:   # Autoren welche automatisch gesetzt werden, falls nichts anderes angegeben wird
  - id: cori
    name: Richard Conrardy
    orcid: 0009-0004-2063-6898
    email: richard.conrardy@phbern.ch
    url: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy
    affiliation:
      - ref: phbern
          
affiliations:
  - id: phbern
    name: University of Teacher Education Bern
    address: Länggassstrasse 35
    city: Bern
    postal-code: 3012
    url: https://www.phbern.ch
    department: Institut Sekundarstufe I
    ror: https://ror.org/05jf1ma54

citation: 
  type: webpage
  URL: https://phbern-rconrardy.github.io/lerngelegenheiten/
  publisher: University of Teacher Education Bern 
appendix-cite-as: display
date: 01/01/2024