---
format: revealjs
title: KI im Mathematikunterricht
date: 02 05 2024
---



# Was ist KI?

## Machine Learning (ML)

```{mermaid}
%%| mermaid-format: svg
flowchart TD
  A[Architektur];
  TD[Training Data];
  T[Tags];
  F[Feedback];
  App[Applikation];
  P[Prompt]
  K[Context]
  O[Output]
  Pa[Parameter]
  R[Regeln]
  I[Instruktionen]
  SM[Sprachmodell]
  UI[User Interface]
    
    
    Training-->Pa;
    A-->SM;
    Pa-->SM;
    SM-->App;
    Anbieter-->App;
    Userdata-->UI;
    App-->UI;
    UI-->O;
    
  subgraph Anbieter
    R;
    I;
  end
  subgraph Hersteller
    A;
    TD;
    T;
    F;
    Pa;
    subgraph Training
    TD;
    T;
    F;
    end
  end
  subgraph Userdata
    P;
    K;
  end
```

## Wichtige Entwicklungen der letzten Jahre

1. Attention  [vgl. @vaswani_attention_2017]
2. Transformer Architektur
3. Large Language Models
4. Multimodal Models

## Wichtige Konzepte

* Temperature [vgl. @wolfram_what_2023 ]
* Generative KI
* Artificial general intelligence 
* $\Rightarrow ML \supset KI\,?$

# KI Applikationen

# Problematische Erklärversuche von KI 

# KI in der Beurteilung


## Summative Beurteilung


1. Datenschutz & Nutzungsrechte
2. Ethische Aspekte
3. KI $\neq$ KI
4. KI $\neq$ Taschenrechner

“participants were not able to detect AI-generated argumentative essays” ([Fleckenstein et al., 2024, p. 3](zotero://select/library/items/I3A9JSFN)) ([pdf](zotero://open-pdf/library/items/YEEQPDDZ?page=3&annotation=EIH6MCDW))

“teachers may not be aware of their inability to identify AI-generated texts among student essays” ([Fleckenstein et al., 2024, p. 4](zotero://select/library/items/I3A9JSFN)) ([pdf](zotero://open-pdf/library/items/YEEQPDDZ?page=4&annotation=NQ9MSDZY))




## Formative Beurteilung

"Bildungsnahe Eltern halfen ihren Kindern bei den Hausaufgaben. Kinder aus bildungsfernen Haushalten waren auf sich gestellt."

:::quelle
 [Wälti in @jones_was_2022,S.3]
:::

"Es soll ausdrücklich keine „ständige Beurteilungssituation“ entstehen"

:::quelle
[@kuratle_kompetenzorientierte_2021,S.10]
:::

## Bibigirl, die vollkommene Puppe {.unlisted}

>Ja, wenn die Puppe gar nichts gesagt hätte, dann hätte Momo an ihrer Stelle antworten können, und es hätte sich die schönste Unterhaltung ergeben
>
>Aber so verhinderte Bibigirl gerade dadurch, daß sie redete, jedes Gespräch.
>
>[...]
>
>Ich glaub', sagte sie leise, man kann sie nicht liebhaben.
>
:::quelle
@ende_momo_1973
:::

## Bibliographie {.unlisted}