---
title: <small>Empirische Untersuchung eines Vier-Phasen-Unterrichtsmodells in Schweizer Sekundarklassen</small>
subtitle: "Nachwuchskolloquium PH Heidelberg"
format: phheidelberg-revealjs
date: 05 06 2024
toc-depth: 1
author:
      - id: cori
        name: Richard Conrardy
        orcid: 0009-0004-2063-6898
        email: richard.conrardy@phbern.ch
        url: https://www.ph-heidelberg.de/mathematik/personen/promovierende/richard-conrardy/
        affiliation:
          - ref: phheidelberg
---

# Ausgangslage

## Schweizer Lehrerbildung

Schweiz, geprägt vom Kantönligeist und von ...

Phasenmodellen:

- PADUA [vgl. @aebli_zwolf_1983]
- AVIVA [vgl. @stadeli_aviva_2020]
- KAKFA [vgl. @reusser__1999]
- SAMBA [vgl. ]
- ...

## Berner Lehrerbildung

Berner (Mathematik-) Didaktik, geprägt von Heuristiken:

- Selbstorganisiertes Lernen [vgl. @hilbe_selbst_2016]
- Reichhaltige Aufgaben [@eckhart_kompetenzorientierung_2020]
- ...

## Forschungsschwerpunkte

- Empirische Forschung
- Phasenmodell
- Offene Aufgaben

# 4F-Modell

## Empirische Forschung

Meta-Metastudie zu flipped classrooms, $n=173$, *included in quantitative Analysis*.

@kapur_fail_2022

## 4F, ein Phasenmodell

1.  [Fail]{style="color: rgb(9, 67, 114)"}
2.  [Flip]{style="text-decoration: underline;color: rgb(255, 197, 11)"}
3.  [Fix]{style="color: rgb(9, 67, 114)"}
4.  [Feed]{style="color: rgb(9, 67, 114)"}

::: quelle
Phasen von @kapur_fail_2022, Einteilung gemäss Autor
:::

::: quelle

[synchron]{style="color: rgb(9, 67, 114)"}

[asynchron]{style="text-decoration: underline;color: rgb(255, 197, 11)"}

:::

Empirisch hergeleitet, jedoch (noch) nicht empirisch geprüft

# Fail

## Productive Failure (PF)

> Productive Failure is an instructional approach in which students engage in **problemsolving** attempts prior to instruction.

:::quelle
@hartmann_productive_2022
:::

- Design in 2 **kollaborative** Phasen:
  -   Phase 1: generation and exploration phase
  -   Phase 2: consolidation phase

::: quelle
[@kapur_designing_2012, S.49]
:::

## Weshalb kollaborativ? 

### individuell

* conceptual knowledge: $p<0.001$, $\eta^2=0.26$

:::quelle
@hartmann_examples_2020
:::

* conceptual understanding: $p<0.001$, $d = 2.00$
* transfer $p<0.001$, $d=1.52$

:::quelle
@kapur_productive_2014
:::

### Unterschied kollaborativ - individuell

* Sekundarklassen (quasi-experimentell): $p = 0.437$

::: quelle
@brand_students_2023
:::

# Flip

## Clipped Classroom

> set of pedagogical approaches that:
>
> (1) move most information-transmission teaching out of class
>
> (2) use class time for learning activities that are active and social and
>
> (3) require students to complete pre- and/or post-class activities to fully benefit from in-class work.
>
> ::: quelle
> @abeysekera_motivation_2015
> :::

## Flipped Classroom Method (FCM)

* Design in 2 Phasen:
  * learn basic content online and prior to class
  * in-class time to clarify students’ understandings [...] enable students to engage deeply [...]

::: quelle
@kapur_fail_2022
:::

## Key findings

1.  quality of implementation \[...\] not consistent
2.  greatest impact \[...\] in-class included a lecture
3.  effects on learning \[...\] due to active learning
4.  problem-solving prior to a lecture \[...\] can be effective

::: quelle
@kapur_fail_2022
:::

# Leitfrage

## Schnittstelle Fail - Flip

1.  [Fail]{style="color: rgb(9, 67, 114)"}
2.  [Flip]{style="text-decoration: underline;color: rgb(255, 197, 11); font-weight: bold;"}
3.  [Fix]{style="color: rgb(9, 67, 114)"}
4.  [Feed]{style="color: rgb(9, 67, 114)"}

::: quelle
Phasen von @kapur_fail_2022, Einteilung gemäss Autor
:::

::: quelle
[synchron]{style="color: rgb(9, 67, 114)"}

[asynchron]{style="text-decoration: underline;color: rgb(255, 197, 11)"}
:::


## Leitfrage

<br>
<br>

Is the 4F-model flipped the right way?

## 

:::: {.columns}
::: {.column width="40%"}
### 4F-Modell

1.  [Fail]{style="color: rgb(9, 67, 114)"}
2.  [Flip]{style="text-decoration: underline;color: rgb(255, 197, 11)"}
3.  [Fix]{style="color: rgb(9, 67, 114)"}
4.  [Feed]{style="color: rgb(9, 67, 114)"}
:::

::: {.column width="60%"}
### Alternativmodell

1.  [Fail (flipped)]{style="text-decoration: underline;color: rgb(255, 197, 11)"}
2.  [Instruct]{style="color: rgb(9, 67, 114)"}
3.  [Fix]{style="color: rgb(9, 67, 114)"}
4.  [Feed]{style="color: rgb(9, 67, 114)"}
:::
::::


::: quelle
[synchron]{style="color: rgb(9, 67, 114)"}

[asynchron]{style="text-decoration: underline;color: rgb(255, 197, 11)"}
:::


# Experiment

## Eckdaten

* 200+ Lernende
* 10+ Klassen
* Experimentell

## Untersuchungsdesign

### Pretest

Eine Woche vor dem ersten Tag der Untersuchung

| Min. | Gruppe 1      | Gruppe 2      |
|------|---------------|---------------|
| 20   | Pretest       | Pretest       |

Es findet eine zufällige Zuteilung der Klasse in zwei Gruppen statt.

<br>

### Erster Tag der Untersuchung

Klasse wird in 2 Gruppen räumlich getrennt.

| Min. | Gruppe 1      | Gruppe 2      |
|------|---------------|---------------|
| 35   | Fail koll.    | Fail ind.     |
| 5    | Mental effort | Mental effort |
| 20   | Flip          | Instruct      |
| 5    | mental effort | mental effort |
| 15   | Posttest      | Posttest      |

<br>

### Zweiter Tag der Untersuchung

Klasse wird zusammen unterrichtet.

| Min. | Gruppe 1      | Gruppe 2      |
|------|---------------|---------------|
| 35   | Fix           | Fix           |
| 5    | mental effort | mental effort |
| 20   | Feed          | Feed          |
| 5    | mental effort | mental effort |
| 15   | Posttest      | Posttest      |

## Forschungsfragen und Hypothesen

1.  Students in the 4F-model score higher in engagement than the non-flipped model.
2.  Students in the 4F-model score higher on (a) procedural fluency and (b) concept knowledge than the alternative model.

## Bibliographie {.unlisted .scrollable}
