---
title: <small>Empirische Untersuchung eines Vier-Phasen-Unterrichtsmodells in Schweizer Sekundarklassen</small>
subtitle: "Zukunftsforum Bildungsforschung"
format: phheidelberg-revealjs
menu: false
date: 21 11 2024
toc-depth: 1
author:
      - id: cori
        name: Richard Conrardy
        orcid: 0009-0004-2063-6898
        url: https://www.ph-heidelberg.de/mathematik/personen/promovierende/richard-conrardy/
        affiliation:
          - ref: phheidelberg
      - id: cori
        name: Christian Spannagel
        orcid: 0000-0002-7299-4943
        url: https://www.ph-heidelberg.de/mathematik/personen/
        affiliation:
          - ref: phheidelberg
title-slide-attributes: 
      data-background-image: "https://www.ph-heidelberg.de/typo3conf/ext/sitepackage/Resources/Public/Images/Paedagogische_Hochschule_Heidelberg_logo.svg"
      data-background-size: 16%
      data-background-position: 98% 5%
code-fold: true
---

# Ausgangslage

## Bildungskontext

**Schweiz**, geprägt vom *Kantönligeist* und von ...

Phasenmodellen: PADUA, AVIVA, KAKFA und SAMBA, ...

:::quelle
PADUA: [@aebli_zwolf_1983], AVIVA: [@stadeli_aviva_2020], KAFKA und SAMBA: [Reusser 1999  nach  @leuchter_rolle_2009]
:::

. . .

**Berner** (Mathematik-) Didaktik, geprägt von Heuristiken:

- SOL - Selbstorganisiertes Lernen 
- Reichhaltige Aufgaben 
- ...

:::quelle
SOL: [@hilbe_selbst_2016; @ammann-tinguely_selbst_2020]; reichhaltige Aufgaben: [@eckhart_reichhaltige_2020; @nydegger_reichhaltige_2019]
:::

# 4F-Modell und Theorie

## Flipped Classroom Method

> set of pedagogical approaches that: [...] (2) use **class time** for learning activities that are **active and social**  [...]
>
> ::: quelle
> [@abeysekera_motivation_2015, S.3]
> :::

::: {.fragment .fade-in}
#### Design in 2 Phasen:
* Phase 1: *learn basic content online and prior to class*
* Phase 2: *in-class time to clarify students’ understandings [...] enable students to **engage** deeply [...]*

:::quelle
[@kapur_fail_2022]
:::

:::


## Empirische Forschung{.smaller}

:::::: {.columns}
::::: {.column width="65%"}

### Metastudie

::: {.fragment .fade-out fragment-index=2}

|                        | g | SE    | N |
|------------------------|-----------|-------|---------|
| Math                   | 0.26      | 0.067 |  65       |
| All Developed countries          | 0.33      | 0.13  |    487     |
| **Pre-class activities** |           |       |         |
| Video                  |   0.22 (M)        |   0.09    |    N     |
| **Post-class activities** |           |       |         |
| Lectures |     0.38      |  0.04     |     532    |
:::

:::::


::::: {.column width="35%"}

:::: {.fragment .fade-right fragment-index=1}

### 4F Modell

::: {.fragment .grow fragment-index=2}
1.  [**Fail**]{}
2.  [**Flip**]{}
:::

::: {.fragment .semi-fade-out fragment-index=2}
3.  [**Fix**]{}
4.  [**Feed**]{}
:::

::::

:::::
::::::

::: quelle
[@kapur_fail_2022, S.14]
:::

## Productive Failure (PF)

> Productive Failure is an instructional approach in which students engage in **problemsolving** attempts **prior to instruction**. 

:::quelle
[@hartmann_productive_2022, S.1219]
:::

::: {.fragment .fade-in}

#### Design in 2 Phasen:

-   Phase 1: *generation and exploration phase*
-   Phase 2: *consolidation phase*

::: quelle
[@kapur_designing_2012, S.49]
:::
:::

## Metastudie PF 

:::{ style="font-size: 0.7em;" }

| Moderating variables  | n   | g    | SE   |
|-----------------------|-----|------|------|
| **Education**          |     |      |      |
| Junior high            | 11  | 0.65 | 0.16 |
| High school            | 9   | 0.38 | 0.17 |
| College                | 3   | 0.06 | 0.40 |
| **Domain**             |     |      |      |
| Science/math           | 20  | 0.50 | 0.13 |
| Other                  | 3   | 0.06 | 0.40 |
| **Duration**           |     |      |      |
| ≤ 1 week               | 16  | 0.43 | 0.16 |
| > 1 week               | 7   | 0.45 | 0.13 |

:::

:::quelle
[@darabi_learning_2018]
:::

## Kollaboration innerhalb von PF

<br>

> Contrary to our expectations, **collaborative** and individual problem-solving students did **not significantly** differ in the conceptual knowledge post-test 
>
:::quelle
[@brand_students_2023]
:::


## Variablen

### Engagement
"PF process depends on students’ **engagement** [...]"

:::quelle
[@kapur_prior_2023]
:::

“in-class time to encourage students to be **active** participants,”

:::quelle
[@abeysekera_motivation_2015]
:::

:::{.fragment .fade-in}

### Mental Load

"flipped classroom [...] may allow better management of cognitive load” 

:::quelle
[@abeysekera_motivation_2015, S.9]
:::

"Productive failure students reported significantly greater cognitive load than VF and DI students."

:::quelle
[@kapur_productive_2014, p.1019]
:::
:::

# Forschungsfrage & -design

## Forschungsfrage

::: {.fragment .fade-out fragment-index=2}
Wie flexibel anpassbar ist das 4F-Modell an die Gegebenheiten des Stundenplans?
:::

<br>

::: {.fragment .fade-out fragment-index=2}
::: {.fragment .fade-in fragment-index=1}
**Was bedeutet das konkret?**
:::
:::


::: {.fragment .fade-in fragment-index=2}
Funktionieren die Mechanismen noch, falls die erste Phase als Kursvorbereitung genommen wird anstelle der zweiten Phase?
:::

## Untersuchungsdesign

:::: {.columns}
::: {.column width="50%"}
### 4F-Modell

1.  [**Fail**]{style="color: #1c87ce"}
2.  [**Flip**]{style="text-decoration: underline;color: #9478b6"}
3.  [**Fix**]{style="color: #1c87ce"}
4.  [**Feed**]{style="color: #1c87ce"}
:::

::: {.column width="50%"}

:::{.fragment .fade-in}


### Alternativmodell

1.  [**Fail (Flipped)**]{style="text-decoration: underline;color: #9478b6"}
2.  [**Instruct**]{style="color: #1c87ce"}
3.  [**Fix**]{style="color: #1c87ce"}
4.  [**Feed**]{style="color: #1c87ce"}

:::
:::
::::



[in class (collaborative)]{style="color: #1c87ce"}

[out of class]{style="text-decoration: underline;color: #9478b6"}


## Hypothesen 


(1) Engagement is highest during in-class activities, irrespective of variant. 
(2) Engagement predicts performance.
(3) The 4F model does not outperform the ALT model. 
(4) Mental load does not predict performance.

# Resultate & Diskussion

## 1. Engagement is highest during in-class activities, irrespective of variant.{style="font-size:0.6em;"} 

:::{.panel-tabset}
#### Resultat 
text

#### Test
```r
1+2
3+4
7+8
```
#### Instrument

5 Fragen mit einer 5-Punkte Likert Skala. Übernommen aus @kapur_productive_2014, $\alpha = 0.79$.

1. Diese Lektion hat mich dazu gebracht, dass ich mich aktiv beteiligen möchte.  
2. Ich war während der Lektion fokussiert.  
3. Ich war aufmerksam während der Lektion.  
4. Ich habe an den Aktivitäten der Lektion teilgenommen.  
5. Ich habe mich während der Lektion konzentriert.

- [ ] stimme überhaupt nicht zu  
- [ ] stimme nicht zu  
- [ ] neutral  
- [ ] stimme zu  
- [ ] stimme voll und ganz zu  


:::

:::{.fragment .fade-up}
::: {style="color: #cc3333; font-size: 2em; font-weight: bold; text-align: center;"}
Verworfen 😿
:::
:::

## 2. Engagement predicts performance.{style="font-size:0.6em;"}


:::{.panel-tabset}
#### Resultat 
text

#### Test
```r
1+2
```
#### Instrument

Aufgaben von @kapur_productive_2014, gleichmässig aufgeteilt nach *procedural knowledge*, *conceptual knowledge* und *transfert knowledge*.

**Aufgabe 1**

Berechne die mittlere absolute Abweichung der folgenden Noten in einer Statistikprüfung:

- 30, 60, 50, 40, 70
- 10, 12, 20, 22

Ein anderer Schüler, Schüler A, verwendet die folgende Methode, um Teilaufgabe a. dieser Frage zu beantworten:

$|30 - 70| + |60 - 70| + |50 - 70| + |40 - 70| + |70 - 70| = 100$  

$100 \div 5 = 20$ Die Lösung ist 20.

Wie unterscheidet sich die Methode von Schüler A von der Berechnung der mittleren absoluten Abweichung? Welche Methode ist besser? Begründe deine Antwort.

**Aufgabe 2**

Beachte die folgenden sechs Datensätze (ein Datensatz pro Zeile):

- **A:** 1, 5, 6, 10
- **B:** 4, 4, 4, 4
- **C:** 101, 102, 103, 104
- **D:** 7, 8, 9, 10
- **E:** 1, 2, 9, 10
- **F:** 1, 2, 3, 4

Welcher der Datensätze hat die kleinste mittlere absolute Abweichung?

- [ ] Datensatz A
- [ ] Datensatz B
- [ ] Datensatz C
- [ ] Datensatz D
- [ ] Datensatz E
- [ ] Datensatz F

Welcher der Datensätze hat die grösste mittlere absolute Abweichung?

- [ ] Datensatz A
- [ ] Datensatz B
- [ ] Datensatz C
- [ ] Datensatz D
- [ ] Datensatz E
- [ ] Datensatz F

**Aufgabe 3**

Ein aus fünf Zahlen bestehender Datensatz hat den Mittelwert \( M = 7 \) und die mittlere absolute Abweichung = 4.

Verwende diese Informationen, um die Fragen a. und b. zu beantworten.

a. Wie verändern sich Mittelwert und mittlere absolute Abweichung, wenn die Zahlen 1 und 13 zu dem Datensatz hinzugefügt werden, sodass ein Datensatz mit sieben Zahlen entsteht?

- **Mittelwert (kreuze eine Antwort an):**
  - [ ] unverändert
  - [ ] nimmt zu
  - [ ] nimmt ab

- **Mittlere absolute Abweichung (kreuze eine Antwort an):**
  - [ ] unverändert
  - [ ] nimmt zu
  - [ ] nimmt ab

b. Wie verändern sich Mittelwert und mittlere absolute Abweichung, wenn die Zahlen 3 und 13 zu dem Datensatz hinzugefügt werden, sodass ein Datensatz mit sieben Zahlen entsteht?

- **Mittelwert (kreuze eine Antwort an):**
  - [ ] unverändert
  - [ ] nimmt zu
  - [ ] nimmt ab

- **Mittlere absolute Abweichung (kreuze eine Antwort an):**
  - [ ] unverändert
  - [ ] nimmt zu
  - [ ] nimmt ab

**Aufgabe 4**

Eine gleiche Anzahl von Schülern nahm am Finale eines Sportwettbewerbs über 100 m Sprint und 100 m Schwimmen teil. Die Zeiten (in Sekunden) der Sieger des 100m Sprints und des 100m Schwimmens sind unten aufgeführt, ebenso wie die Durchschnittszeiten und die Standardabweichung der Finalisten der beiden Wettbewerbe.

|            | 100m Sprint | 100m Schwimmen |
|------------|-------------|----------------|
| Gewinner   | 11s         | 40s            |
| Mittelwert der Finalisten, \( M \) | 12s         | 45s            |
| Mittlere absolute Abweichung der Finalisten | 1s          | 10s            |

Unter der Annahme, dass alles andere gleich ist, wer von den beiden Gewinnern ist der bessere Sportler?

- [ ] Der Sprint-Gewinner
- [ ] Der Schwimm-Gewinner
- [ ] Beide
- [ ] Es gibt nicht genügend Informationen, um dies zu entscheiden

**Aufgabe 1**

- **Bei der Berechnung der mittleren absoluten Abweichung, erkläre, warum es wichtig ist, den Absolutbetrag der Differenzen zum Mittelwert zu rechnen.**

- **Bei der Berechnung der mittleren absoluten Abweichung, erkläre, warum es wichtig ist, die Summe durch die Anzahl der Werte zu teilen.**

**Aufgabe 2**

Die Eigentümer von zwei Kinos, A und B, argumentieren, dass ihr jeweiliges Kino eine gleichmäßigere Besucherzahl aufweist. Sie erfassten die täglichen Besucherzahlen ihrer Kinos an 11 zufälligen Tagen. Die Ergebnisse ihrer Datenerhebung sind im Folgenden dargestellt:

| Kino A      | Kino B      |
|-------------|-------------|
| Mittelwert, M               | 72          | 75          |
| Mittlere absolute Abweichung | 10          | 14          |

**Welches Kino hat Ihrer Meinung nach eine gleichmäßigere Anwesenheit?**

- Kino A
- Kino B
- Beide hatten eine ähnlich gleichmäßige Besucheranzahl
- Keine der oben genannten Lösungen

**Aufgabe 3**

Beachte die folgenden sechs Datensätze (ein Datensatz pro Zeile):

| A   | 1  | 5  | 6  | 10 |
| --- | -- | -- | -- | --- |
| B   | 4  | 4  | 4  | 4  |
| C   | 101 | 102 | 103 | 104 |
| D   | 7  | 8  | 9  | 10 |
| E   | 1  | 2  | 9  | 10 |
| F   | 1  | 2  | 3  | 4  |

**Welche Datensätze haben die gleiche mittlere absolute Abweichung? (1 Antwort)**

- Datensätze A, E, F
- Datensätze C, D, F
- Datensätze A, B
- Datensätze C, F
- Datensätze B, D, F
- Datensätze B, E, F

**Aufgabe 4**

Ein aus fünf Zahlen bestehender Datensatz hat den Mittelwert M = 7 und die mittlere absolute Abweichung = 4. Verwende diese Informationen, um die Fragen a. bis c. zu beantworten.

- **Wenn jede der fünf Zahlen um 2 erhöht wird, wie lauten der neue Mittelwert M und die neue mittlere absolute Abweichung?**

    - M = 7, Mittlere absolute Abweichung = 4
    - M = 9, Mittlere absolute Abweichung = 4
    - M = 7, Mittlere absolute Abweichung = 6
    - M = 9, Mittlere absolute Abweichung = 6

- **Wenn jede der fünf Zahlen mit 5 multipliziert wird, wie lauten der neue Mittelwert und die neue mittlere absolute Abweichung?**

    - M = 7, Mittlere absolute Abweichung = 4
    - M = 35, Mittlere absolute Abweichung = 4
    - M = 7, Mittlere absolute Abweichung = 20
    - M = 35, Mittlere absolute Abweichung = 20

- **Wie verändern sich Mittelwert und mittlere absolute Abweichung, wenn die Zahlen 5 und 9 zu dem Datensatz hinzugefügt werden, sodass ein Datensatz mit sieben Zahlen entsteht?**

Mittelwert (kreuze eine Antwort an):

- unverändert
- nimmt zu
- nimmt ab

Mittlere absolute Abweichung (kreuze eine Antwort an):

- unverändert
- nimmt zu
- nimmt ab

**Aufgabe 5**

Davids Ergebnisse für Mathematik, Physik und Chemie in den Abschlussprüfungen sind unten aufgeführt. Die Leistungen seiner Klasse in diesen drei Fächern sind ebenfalls unten aufgeführt:

| Fach              | Mathematik | Physik | Chemie |
|-------------------|------------|--------|--------|
| Davids Punkte     | 95         | 90     | 85     |
| Klassenmittelwert | 80         | 80     | 80     |
| Mittlere absolute Abweichung der Klasse | 15 | 5 | 4 |

- **In welchem Fach hat David im Vergleich zu seiner Klasse am besten abgeschnitten?**

    - Mathematik
    - Physik
    - Chemie

- **In welchem Fach hat David im Vergleich zu seiner Klasse am schlechtesten abgeschnitten?**

    - Mathematik
    - Physik
    - Chemie



:::


:::{.fragment .fade-up}
::: {style="color: #0c710b; font-size: 2em; font-weight: bold; text-align: center;"}
Bestätigt 😸
:::
:::

## 3. The 4F model does not outperform the ALT model. {style="font-size:0.6em;"}


:::{.panel-tabset}
#### Resultat 
text

#### Test
```r
1+2
```

:::


:::{.fragment .fade-up}
::: {style="color: #0c710b; font-size: 2em; font-weight: bold; text-align: center;"}
Bestätigt 😺
:::
:::

## 4. Mental load does not predict performance.{style="font-size:0.6em;"}


:::{.panel-tabset}
#### Resultat 
text

#### Test
```r
1+2
```
#### Instrument

9-Punkte Likert Skala genutzt von @kapur_productive_2014 aus @paas_training_1992.

>[...] nine-point rating scale that is commonly used in the cognitive load literature as a measure of cognitive load (Paas, 1992).

::::quelle
@kapur_productive_2014
::::

In dieser Lektion hatte ich eine:

- [ ] sehr, sehr geringe mentale Anstrengung  
- [ ] sehr geringe mentale Anstrengung  
- [ ] geringe mentale Anstrengung  
- [ ] eher geringe mentale Anstrengung  
- [ ] weder hohe noch niedrige mentale Anstrengung  
- [ ] eher hohe mentale Anstrengung  
- [ ] hohe mentale Anstrengung  
- [ ] sehr hohe mentale Anstrengung  
- [ ] sehr, sehr hohe mentale Anstrengung  


:::


:::{.fragment .fade-up}
::: {style="color: #0c710b; font-size: 2em; font-weight: bold; text-align: center;"}
Bestätigt 😽
:::
:::

## Diskussion {.incremental}

### Limitationen

::: {.incremental}
* out-of-class im Schulgebäude
* "fremde" Lehrperson
* Erhebungsinstrumente
:::



### Ausblick

::: {.incremental}
* andere Phasen flippen
* andere Schulstufe
* anderes Fachgebiet

:::

## Bibliographie {.unlisted .scrollable}
