---
format: 
  revealjs
title: Inhalte effizient onlinebringen
subtitle: Treffpunkt Hochschuldidaktik
date: 18 03 2024
---

# Learning Outcomes

## Expectation management

::: {.incremental}
* ~~besser~~ als Powerpoint, Word etc.
* ~~schlechter~~
* erfrischend anders!
:::

## Learning Outcomes {.unlisted}

1.  Wir erstellen eine Webseite in 5 Minuten.
2.  Wir schreiben in 7 Sprachen.




# Webseite

## 3 step plan {.unlisted}

1.  Webseite erstellen
2.  Webseite auf Ilias stellen
3.  Webseite auf dem Internet publizieren

```{r}
#| echo: false
#| code-fold: true
#| code-summary: "Quellcode für den Countdown"
library (countdown)
countdown(
  right = 0,
  top = 0,
  font_size = "1.5em",
  margin = "0%",
  minutes = 20, 
  seconds = 0
)
```

# Inhalte erstellen

## Dateien

### Webseite anpassen

1. _quarto.yml
2. styles.scss
3. index.qmd
4. neue Seite erstellen und ins Menü einfügen

### Präsentationsfolien erstellen

## Do-it-yourself

1.  Markdown
2.  Yaml
3.  CSS
4.  HTML
5.  $\LaTeX$
6.  `Python`
7.  `Javascript`(Mermaid JS)
8. Bibtex

## YAML

## Mark️up

# Recht

## Datenschutzrecht {.unlisted}

> Dieses Gesetz gilt für jedes Bearbeiten von Personendaten durch Behörden.
>
> ::: quelle
> [Art. 4 Abs.1 KDSG](https://www.belex.sites.be.ch/app/de/texts_of_law/152.04/versions/7)
> :::

> Personendaten sind Angaben über eine bestimmte oder bestimmbare natürliche oder juristische Person.
>
> ::: quelle
> [Art.2 Abs.1 KDSG](https://www.belex.sites.be.ch/app/de/texts_of_law/152.04/versions/7)
> :::

## Urheberrecht {.unlisted}

> Der Arbeitnehmer ist für den Schaden verantwortlich, den er absichtlich oder fahrlässig dem Arbeitgeber zufügt.
>
> ::: quelle
> [Art.321e Abs.1 OR](https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_321_e)
> :::

> Das Zitat muss der Erläuterung, der Veranschaulichung oder als Hinweis dienen und darf nicht länger als nötig sein. Zudem müssen Sie das Zitat als solches bezeichnen und die Quelle angeben. Nennt die Quelle den Urheber, müssen Sie auch diesen erwähnen.
>
> ::: quelle
> @eidgenössischesinstitutfürgeistigeseigentum
> :::

## PHBern {.unlisted}

> An der PHBern entscheiden gemäss Art. 8 Abs. 1 Bst. o des PH-Statuts (PHSt; abrufbar unter www.phbern.ch/rechtssammlung \> Ziff. 1.0) grundsätzlich die **Institutsleiterinnen und Institutsleiter** über die Nutzung immaterieller Arbeitsergebnisse \[...\]
>
> ::: quelle
> Geistiges Eigentum Merkblatt
> :::

## Wo geht die Reise hin?

* Github 
* PDF-Vorlagen
* 

## Diskussion

* Potential für Studierende?
* Potential für Dozierende?
* Welche Features sind wichtig?

## Bibliographie {.unlisted}
