---
title: Mikroplanung Mathematik
subtitle: Lernumgebungen entwickeln
format: html
categories:
  - Modul - Mikroplanung
  - Fach - Mathematik
editor: 
  markdown: 
    wrap: 72
draft: false
---

::: {style="text-align: center;"}
[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){.knopf
.knopf-klein target="_blank"}
[Materialraum](https://ilias.phbern.ch/goto_phbern_grp_2127034.html){.knopf
.knopf-klein target="_blank"}
:::

::: panel-tabset
# Blockkurs

::: {.callout-tip collapse="false"}
## Flipped Classroom (Blockkurs)

Diese Lerngelegenheit ist mit Flipped Classroom Methode konzipiert.

> 1.  move most information-transmission teaching out of class
> 2.  use class time for learning activities that are active and social
>     and
> 3.  require students to complete pre- and/or post-class activities to
>     fully benefit from in-class work.
>
> [@abeysekera_motivation_2015, S.3]
:::

# SOL

::: {.callout-tip collapse="false"}
## Selbstorganisiertes Lernen (SOL-Kurs)

Dies ist eine selbstorganisierte Lerngelegenheit. Das heisst, die
Studierenden "steuern ihr Lernhandeln jedoch weitgehend selber, indem
sie selbständig Lernschritte definieren, ausführen, regulieren und
beurteilen." [@hilbe_selbst_2011, S.8]

Dem Dozierenden "kommt dabei die Aufgabe zu, geeignete Rahmenbedingungen
für das Gelingen des Lernprozesses zu schaffen, Lernstrategien zu
vermitteln und die Schülerinnen und Schüler bei Schwierigkeiten zu
unterstützen." [@hilbe_selbst_2011, S.8]

Kurz bedeutet dies, dass Sie stets Hilfe abholen können, sei es
inhaltlich, organisatorisch oder anderer Art.
:::
:::

# Workload

Sie veröffentlichen eine Lernumgebung von 2 bis 4 Lektionen unter einer freien Lizenz (Vorschlag: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)) und zitieren nach APA 7 [vgl. @american_psychological_association_publication_2020].

*Vorschlag*: Sie können ihre Lernumgebung auf [Switchportolio](https://portfolio.switch.ch/) erstellen und veröffentlichen.

Sie planen eine bis zwei Doppellektionen für eine niveaudurchmischte Klasse und geben folgende Materialien ab: 

* Einführender Lehrpersonenkommentar,  
* Lektionsplanung, 
* Unterrichtsmethoden,  
* Unterrichtstechniken,  
* Lernmaterialien,  
* Medien  
* Zwei Vertiefungen (Motivation, Wirksamkeit, Lernphasen oder Wissenserwerb) 

Sie begründen Ihre Planungen differenziert mathematikdidaktisch, lernpsychologisch und mit Bezügen zu den Querschnittsthemen. 

Folgende Beurteilungskriterien dienen Ihnen zur Orientierung:

* Die Lernumgebung enthält bedeutsame Inhalte, welche mit dem Lehrplan verbunden sind. 
* Die Lernumgebung ist fachlich-inhaltlich korrekt. 
* Die Lernumgebung ist zielgruppengerecht strukturiert.  
* In der Lernumgebung sind die Lernerwartungen zielgruppengerecht formuliert. 
* Der Lernprozess bei der Lernumgebung ist in sinnvolle Lernphasen gegliedert. 
* Die Lernumgebung enthält analoge wie digitale, fachliche, überfachliche und fächerübergreifende Teile mit entsprechenden sprachsensiblen Aufgaben. 
* Die Lernumgebung fördert partizipatives und individualisiertes Lernen. 
* In der Lernumgebung werden Sozialformen, Methoden, Medien und Materialien lernfördernd und abwechslungsreich eingesetzt. 
* Die Lernumgebung und zusätzlichen Erklärungen zeigen wie Lernprozesse fachwissenschaftlich, fachdidaktisch, allgemeindidaktisch, mediendidaktisch und lernpsychologisch gestaltet und begründet sind. 