---
format: html
title: Sprachsensibler Mathematikunterricht
copyright: >
  Dieses Lernmodul basiert auf dem Buch "Sprachbildung in der Lehramtsausbildung Mathematik" von Florian Schacht und Susanne Guckelsberger. 
  Dieses Buch steht unter einer CC BY 4.0 Lizenz: http://creativecommons.org/licenses/by/4.0/deed.de
---

:::: {.callout-note}

## Lernziele

Wir 

* strukturieren fachliche Inhalte ebenso korrekt wie zielgruppengerecht und formulieren entsprechende Lernerwartungen.
* entwickeln sprachsensible Aufgaben.

:::quelle
[@phbern_leitfaden_2022, S.6]
:::
::::

# Reflexion eigene Schulzeit

Welche Sprachen, bzw. Sprachebenen wurden bei dir in der Schule benutzt?

Wann sprach die Lehrperson Hochdeutsch, wann sprach sie Dialekt?

Lesen Sie @pyers_language_2009. Ausgehend von diesem Artikel, argumentieren Sie in wiefern Sprache notwendig ist, um Schulmathematik zu verstehen.

Übersetzen Sie folgende Aussage ins Deutsche. 
$$\lim_{x \to \infty} f(x) = L \quad \Leftrightarrow \quad \forall \epsilon > 0 \; \exists M > 0 \; \vert \; \forall x > M \; \left| f(x) - L \right| < \epsilon.$$

Übersetzen Sie folgenden Linuxbefehl ins Deutsche: 

```bash
rm -rf /
```

## Sprachsensibler Fachunterricht

Sprachsensibler Fachunterricht (SFU) geht auf die Arbeit von Leisen zurück  und war ursprünglich als Handbuch für Deutsch im Fachunterricht (DFU) für Deutsch als "Fremd- umd Fachsprache an deutschen Auslandschulen" gedacht, wurden jedoch später für Deutsch als Zweitsprache genutzt [vgl. @rottger_sprachsensibler_2019]. 


> Der Begriff *sprachsensibler Unterricht* steht für unterschiedliche Unterrichtskonzepte, die Sprache bewusst als Mittel des Denkens und Kommunizierens einsetzen, um fachliches und sprachliches Lernen zu verknüpfen. [@giesau_basiswissen_2018, CC BY-ND 4.0]

Zwischen Sprachbildung, Sprachförderung und sprachsensiblem Unterricht wird nicht durchgängig unterschieden. Ähnlich verhält es sich mit *sprachbewusst* und *sprachaufmerksamem* Unterricht. “Was unübersichtlich klingt, *ist* in der fachlichen Diskussion auch so,” [@rottger_sprachsensibler_2019, S. 91]

Die Dokumente zu SFU sind mehrheitlich theoretisch oder praxisorientiert[@rottger_sprachsensibler_2019]. Nach zahlreichen SFU-Projekten hat sich der Abstand zwischen Lernenden mit und ohne Migrationshintergrund nicht reduziert. Empirische Evidenz für den Erfolg von Massnahmen scheint noch nicht vorzuliegen. 


## Checkliste zur Entlastung von Texten

@abshagen_praxishandbuch_2015 beschreibt in 

> * Kontext aus der Lebenswelt der SuS wählen. 
> * Kurze Sätze bilden, Nebensätze und Verschachtelungen vermeiden' 
> * Verben im Aktiv nutzen statt unpersönlicher oder abstrakter Ausdrücke (du rechnest "')' 
> * Texte durch Absätze vorstrukturieren' Wichtiges farbig oder fett gedruckt hervorheben' 
> * Genitiv und Partizi pialkonstruktionen vermeiden' 
> * Wenig Bezugsformen verwenden, stattdessen Wiederholungen wählen' 
> * Bei Fachwörtern oder schwierigen Wörtern Erklärungen in Klammern oder als Fußnoten mitliefern' 
> * Wenig zusammengesetzte Wöfter verwenden' 
> * Bei Arbeitsaufträgen bereits bekannte Operatoren einsetzen' Unterstützung durch eine informative Figur anbieten'
>
:::quelle
[@abshagen_praxishandbuch_2015, S.18]
:::

# Sprachsensible Aufgaben

@schacht_sprachbildung_2022