---
title: "Chancen und Risiken standardisierter Testverfahren und Leistungsmessung"
subtitle: "Teil Mathematik"
format: html
---

# Organisatorisches

<div style="text-align: center;">
[Organisationsblatt](https://phbern365.sharepoint.com/:x:/s/IS1_Z_FachteamMathematik/EZTPyLRviQ5CsP7FA8-JGkYBpYwrk6tB_D_M9r-QOa7Tjw?e=bo4L69){class="knopf " target="_blank"}

[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){class="knopf knopf-klein" target="_blank"}
[Materialraum](https://ilias.phbern.ch/goto_phbern_fold_2177856.html){class="knopf knopf-klein" target="_blank"}
</div>


## Medienempfehlung:

Als zusätzliche Leseempfehlung werden folgende drei Medien in absteigender Reihenfolge der Wissenschaftlichkeit genannt:

* [Imlig, F., & Ender, S. (2018). Towards a national assessment policy in Switzerland: Areas of conflict in the use of assessment instruments. Assessment in Education: Principles, Policy & Practice, 25(3), 272–290.](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/ESZlmEqQn2xDsGMB5Gmqp5IB6dxjEEZ0XkFH12KzKiqNbw?e=0RX2mW)
* [Prüfungen abschaffen, Video (Jörn Loviscach)](https://phbern365.sharepoint.com/:v:/s/IS1_Z_FachteamMathematik/EXfwrFDtzjNArMaGyWiosRcB22QMC9y1QE48GTob05l-2A?e=th92S0)
* [Standardized Testing, Video (John Oliver)](https://phbern365.sharepoint.com/:v:/s/IS1_Z_FachteamMathematik/EUjsTQSfUqBKqO5O4IHLjGcByhdi_l6QqreFOfjW0uiNrA?e=QdjpoN)

Falls Sie eine oder mehre Quellen als Vorbereitung für den Kurs nutzen, können wir am Anfang der Doppellektion offene Fragen klären oder eine kurze Diskussion lancieren.

## Dokumente und Quellen

- [Präsentationsfolien](slides.qmd)
  - [ÜGK Schweiz](https://www.uegk-schweiz.ch)
    - [ÜGK 2016Schlussbericht](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EUJDu0pLGFFFjiDAmUHQlpsBRv9a3GJ-5AzNuCNfcwFa5Q?e=4l9mvo)
  - [Übertritt PRIM - Sek I Kontrollprüfungen](https://www.akvb-unterricht.bkd.be.ch/de/start/unterricht/beurteilung-uebertritte/uebertritt-prim-sek-i-kontrollpruefung.html)
    - [Monitoring Kontrollprüfungen 2023](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/ETVJKe4XX45GmoWGze8pq6MB4lLQXPt7U9aqCshkvrVUEQ?e=3CJbXt)
    - [Referenzrahmen Mathematik](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EXiCoKrAXTlKj5-TaomEti0B2MoqY4YFD-Mn3ScFbtcD5g?e=wsclIZ)
    - [BFS -  Selektion auf der Sekundarstufe I](https://www.bfs.admin.ch/bfs/de/home/statistiken/wirtschaftliche-soziale-situation-bevoelkerung/gleichstellun-frau-mann/bildung/bildungsstand.assetdetail.24485156.html)
  - [PISA](https://www.oecd.org/pisa/publications/pisa-2018-results.htm)
    - [Country Note - Switzerland](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/EcYeJ2XBvdRPp28NTYD9W04BO1QMAOz18YZOlDue41v8SA?e=pwl4Cz)
    - [PISA 2012: Veröffentlichte Beispielaufgaben - Mathematik](https://phbern365.sharepoint.com/:b:/s/IS1_Z_FachteamMathematik/Ee4USkcuFWVFti6wvTDG1BkB6E7C4Y4XN4WX9UKq44GayA?e=GMfeYZ)
  - [Übertritt Sek I - Sek II](https://www.akvb-unterricht.bkd.be.ch/de/start/unterricht/beurteilung-uebertritte/uebertritt-sek-i-sek-ii.html)
    - [BFS - Maturitätsquote](https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/bildungsindikatoren/themen/bildungserfolg/maturitaetsquote.html)
    - [BFS - Löhne nach Kompetenzniveau, Bildung und beruflicher Stellung ](https://www.bfs.admin.ch/bfs/de/home/statistiken/wirtschaftliche-soziale-situation-bevoelkerung/gleichstellung-frau-mann/loehne/kompetenzniveau-bildung-berufliche-stellung.html)
    - [Artikel: der Bund](https://www.derbund.ch/die-ungerechtigkeit-ist-in-bern-eher-groesser-als-in-zuerich-325562265525)
- [Ablageordner](https://phbern365.sharepoint.com/:f:/s/IS1_Z_FachteamMathematik/Epxjeu3y-JNPtrCy1bxQa2sBygOsemMHtlOgRaZDg_QKgA?e=2dUzJj)


Weitere Dokumente:

- [Das Monitoring der Grundkompetenzen in neuer Gestalt](https://www.edk.ch/de/die-edk/blog/271023)
- [Evaluationen Kanton Bern](https://www.bkd.be.ch/de/start/themen/statistik-bildung-und-kultur/daten-publikationen/evaluationen-bildungsmonitoring.html)
