---
title: "Verstehensorientiert prüfen in Zeiten von KI"
subtitle: "Python im Mathematikunterricht"
format: html
categories:
  - Modul - Formative Beurteilung
  - Modul - Summative und prognostische Beurteilung
  - Label - Digitalität
  - Fach - Mathematik
authors:
    - name: Richard Conrardy
      orcid: 0009-0004-2063-6898
      id: 00383195
      email: richard.conrardy@phbern.ch
      url: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy
      affiliations:
        - ref: phbern
    - name: Joël Adler
      url: https://www.phbern.ch/ueber-die-phbern/personen/joel-adler
      affiliations:
          - ref: phbern
          
copyright: Dieser Kurs basiert auf dem Kurs von Peter Giger (https://pgigeruzh.github.io/informatik/) welcher unter einer  Creative Commons Attribution 4.0 International license (https://creativecommons.org/licenses/by/4.0/) steht.
citation: 
  author:
    - Peter Giger
    - Richard Conrardy
    - Joel Adler
---

::: {style="text-align: center;"}
[Organisationsblatt](https://phbern365.sharepoint.com/:x:/r/sites/IS1_Z_FachteamMathematik/Freigegebene%20Dokumente/General/Lerngelegenheiten/Beurteilung%20Mathematik%20Verstehensorientiert%20pr%C3%BCfen%20in%20Zeiten%20von%20KI/Studierende_Schreibrechte/Organisationsblatt%20Verstehensorientiert%20KI.xlsx?d=wf38b17f72e1f471bbdb882f9f7a981de&csf=1&web=1&e=6yfZvS){.knopf target="_blank"}

[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){.knopf .knopf-klein target="_blank"} [Materialraum](https://ilias.phbern.ch/goto_phbern_fold_2177856.html){.knopf .knopf-klein target="_blank"} [Porta-QT-Digitalität](https://porta.phbern.ch/content/page/62694b41dd910c2dedc2d1d1){.knopf .knopf-klein target="_blank"}
:::

# Wochenüberblick

| Woche | Thema                                           |                               Slides                               |                   Unterlagen                    |                                   Vorbereitung                                   |     |
|:----------:|:-----------|:----------:|:----------:|:----------:|------------|
|   1   | Variablen und Conditionals                      | [<i class="bi bi-easel3-fill"></i>](woche_01.qmd){target="_blank"} |                                                 | [<i class="bi bi-file-earmark-check-fill"></i>](#vorbereitungsauftrag---woche-1) |     |
|   2   | Loops und Listen                                | [<i class="bi bi-easel3-fill"></i>](woche_02.qmd){target="_blank"} |                                                 |                                                                                  |     |
|   3   | Funktionen und Projektauftrag                   | [<i class="bi bi-easel3-fill"></i>](woche_03.qmd){target="_blank"} |                                                 |                                                                                  |     |
|   4   | Projekt 1 (asynchron)                           |                                                                    | [<i class="bi bi-folder-fill"></i>](#projekt-1) |                                                                                  |     |
|   5   | Überschlagen üben und Sieb des Eratosthenes     |         [<i class="bi bi-easel3-fill"></i>](woche_05.qmd)          |                                                 |                                                                                  |     |
|   6   | Perfekte und narzistische Zahlen, Exp. Wachstum |                                                                    |                                                 |                                                                                  |     |
|   7   | Stammbrüche und Vermutung von Collatz           |         [<i class="bi bi-easel3-fill"></i>](woche_07.qmd)          |                                                 |                                                                                  |     |
|   8   | Brute force Gleichungen lösen & Kombinatorik    |         [<i class="bi bi-easel3-fill"></i>](woche_08.qmd)          |                                                 |                                                                                  |     |
|   9   | Projekt 2 (asynchron)                           |                                                                    | [<i class="bi bi-folder-fill"></i>](#projekt-2) |                                                                                  |     |
|  10   | fällt im FS24 aus?                              |                                                                    |                                                 |                                                                                  |     |
|  11   | Algorithmen                                     |         [<i class="bi bi-easel3-fill"></i>](woche_10.qmd)          |                                                 |                                                                                  |     |
|  12   | Quarto                                          |         [<i class="bi bi-easel3-fill"></i>](woche_11.qmd)          |                                                 |                                                                                  |     |

: {.striped .hover .table-sm}

<hr>

# Wocheninhalte

## Vorbereitungsauftrag - Woche 1 {#vorbereitungsauftrag---woche-1}

Im Fokus der Lerngelegenheit steht das Programmieren. Installieren Sie **vor** der ersten Woche Rstudio und Python auf Ihrem Computer.

::: panel-tabset
## Windows 🪟

Grobe Installationsanleitung unter Windows:

1.  Installieren Sie R, [Webseite](https://cran.rstudio.com/bin/windows/base/).
2.  Installieren Sie RStudio, [Webseite](https://posit.co/download/rstudio-desktop/).
3.  Installieren Sie RTools, [Webseite](https://cran.r-project.org/bin/windows/Rtools/).
4.  In der *Console* in Rstudio: `install.packages("reticulate")`.
5.  In der *Console* in Rstudio: `reticulate::install_miniconda()`.

## MacOS 🍎

Grobe Installationsanleitung unter MacOS:

Öffnen Sie ein Terminal (Befehlszeile). Geben Sie folgende befehle ein:

1.  [Homebrew](https://brew.sh/) im *Terminal* installieren: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2.  [RStudio (+R)](https://formulae.brew.sh/cask/rstudio#default) im *Terminal* installieren: `brew install --cask rstudio`
3.  In der *Console* in Rstudio: `install.packages("reticulate")`.
4.  In der *Console* in Rstudio: `reticulate::install_miniconda()`.

Empfehlung: Installieren Sie Software grundsätzlich über [Homebrew](https://brew.sh/) (Paketmanager für MacOS).

Alle mit Homebrew installierten Programme können mit folgendem Terminalbefehl geupgradet werden: `brew update && brew upgrade && brew upgrade --cask && brew cleanup`

## GNU/Linux 🐧

Komm vorbei für einen gratis ☕️.

Installation hängt von der Distro ab.
:::

::: callout-note
Bei technischen Schwierigkeiten dürfen Sie sich gerne an Dozierende wenden. ChatGPT 3.5 liefert ebenfalls wertvolle Hilfestellungen zu Softwareproblemen.
:::

Überprüfen Sie Ihre Installation in dem Sie ein beliebiges Pythonprogramm ausführen, z.B.

``` python
print("Hello, World!")
```

------------------------------------------------------------------------

## Packages installieren (numpy)

Im `Terminal`folgenden Befehl eingeben: `pip install numpy`. Falls Fehler gemeldet werden folgendes beachten:

1.  Im `Terminal` folgendes eingeben: \`pip --version\`\`
2.  In der Ausgabe den *path*, insb. Versionsnummer merken, z.B. `from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
3.  In Rstudio im Menü unter `Tools > Global Options` bei `Python` genau diesen Interpreter wählen und speichern.
4.  Nun Library im `Terminal`mit `pip install numpy`installieren.

------------------------------------------------------------------------

## Projekt 1 {#projekt-1}

Entwickeln Sie Übungssituation im Kontext einer formativen oder summativen Beurteilung mit direktem Bezug zu den Indikatoren [MA.1.A.2.h](https://be.lehrplan.ch/101tLRW4xvunbRb5TfwTddzSsnKWUGRXA) oder [MA.1.A.2.i](https://be.lehrplan.ch/1017J6SBfwtVNTyD2VCwcbJdt6SD5mwXd). In dieser Übung müssen die Lernenden ein Computerprogramm erstellen oder ein von Ihnen erstelltes Programm anpassen und/oder benutzen.

Halten Sie schriftlich fest, wie diese Übung zur summativen Beurteilung beiträgt und gehen Sie dabei auf Chancen und Risiken von automatisierten Verfahren ein.

Sie können die Arbeit als Partnerarbeit erledigen.

<details>

<summary>Lösungsvorschlag 1</summary>

Dieser Lösungsvorschlag stammt von Jessica Eichler, lizenziert unter [CC BY-SA 4.0 Lizenz](https://creativecommons.org/licenses/by-sa/4.0/).

``` python
# Lösung von Jessica Eichler unter einer CC BY-SA 4.0 Lizenz
import random
auftrag = input("Löse die nachfolgenden Aufgaben!")
while True:
  random_numberone=random.randint(1,1000)
  random_numbertwo=random.randint(1,1000)
  print(random_numberone, "von", random_numbertwo,flush=True)
  lösung= float(input("Schätze den prozentualen Anteil ab. Wie viel erhältst du?"))
  richtiges_resultat = (random_numberone / random_numbertwo) * 100
  if abs(lösung - richtiges_resultat)<10:
    print("Gut gemacht ... weiter so!",flush=True)
  else:
    print("Versuch es nochmals.",flush=True)
  weiter = input ("Möchten sie fortfahren? (ja/nein)")
  if weiter == "ja":
    continue
  else:
    break
```

</details>

<details>

<summary>Lösungsvorschlag 2</summary>

Dieser Lösungsvorschlag von Liv Streit ist unter einer CC0 Lizenz.

``` python
import random
def Aufgabe():
  while True:
    random_num1 = random.randint(1,100)
    random_num2 = random.randint(1,100)
    operation = random.choice (['+', '-'])
    try:
      user_answer = int(input(f"Was ist {random_num1} {operation} {random_num2}?"))
      richtiges_resultat = eval(f"{random_num1} {operation} {random_num2}")
      abweichung = abs(float(user_answer)-richtiges_resultat)
      abweichung_prozentsatz = (abweichung / richtiges_resultat) * 100
      toleranz = 10
      if -toleranz <= abweichung_prozentsatz <= toleranz:
        print ("Juhu, deine Antwort ist richtig!",flush=True)
        break
      else:
        print ("Deine Antwort ist leider falsch, versuche es gleich noch einmal.",flush=True)
    except ValueError:
      print("gib bitte eine Zahl ein.")
Aufgabe()
```

</details>

------------------------------------------------------------------------

## Projekt 2 {#projekt-2}

Entwickeln Sie Übungssetting im Kontext einer formativen Beurteilung mit direktem Bezug zum Indikator [MA.3.B.2.e](https://be.lehrplan.ch/101qxA33rpuZHJ7LqqFSn39kpbUyt7DwW). In dieser Übung müssen die Lernenden ein Computerprogramm erstellen oder ein von Ihnen erstelltes Programm anpassen und/oder benutzen.

Halten Sie schriftlich fest:

-   wie diese Übung zur formativen Beurteilung beiträgt.
-   wie Sie mit diesem Übungssetting Unterrichtsmaterial und Medien zur Rückmeldung verwenden und auf eine konkrete Unterrichtssituation anpassen.
-   wie dieses Übungssetting die Entwicklung bildungssprachlicher Kompetenzen im Zusammenhang mit fachlichem Lernen fördert.

::: callout-tip
## Leistungsnachweis: Formative Beurteilung

Dieses Projekt kann integraler Bestandteil des Modulleistungsnachweises der formativen Beurteilung sein. Für offizielle Informationen zum Leistungsnachweis, lesen Sie die betreffende [Iliasseite](https://ilias.phbern.ch/goto_phbern_crs_1784163.html).
:::

Interessante Aufgaben kann man hier finden:

- [Informatikbiber](https://www.informatik-biber.ch/aufgabensammlung/) (Lizenz CC BY-NC-SA)
- [Mathekänguru](https://www.mathe-kaenguru.de/chronik/aufgaben/index.html) 

------------------------------------------------------------------------

