---
format: html
title: Dokumentenmappe mit BU21
authors:
  - Aline Löw
  - Daniel Ingrisani
  - Irene Althaus
citation: 
  author:
    - Aline Löw
    - Daniel Ingrisani
    - Irene Althaus
---
Ziel: Informationen und Einblicke in das Notenerfassungssystem «Beurteilung 21».

Setting: Selbststudium

Termin:  Mi 14:15-16:00
 
Vorbereitungsauftrag:
Im Lernmodul zur elektronischen Erfassung der Noten erhalten Sie einen Test-Zugang zum Portal BU21 der BKD.

1. Eröffnen Sie bis am 07.03.2024 ein BE-Login. Dieses erlaubt Ihnen die Nutzung unserer Testumgebung. Falls Sie dazu eine Anleitung möchten, siehe unten.

2. Tragen Sie sich anschliessend in diesem Formular ein, damit die Test-Umgebung für Sie bereitgestellt werden kann.

Sollten Sie bereits über ein BE-Login verfügen, können Sie dieses im selben Formular eintragen.

Die Registrierung des BE-Logins dauert in der Regel nicht länger als 5min, jedoch nimmt es einige Zeit in Anspruch, bis der Account danach einsatzbereit ist.

Der Zugriff auf das Portal BU21 ist für Sie ab dem 01.04.2024 möglich.

# Dokumentenmappe

Die Dokumentenmappe wird jeweils zum Schuljahresende erstellt und den Schülerinnen und Schülern ausgehändigt. Im Zyklus 3 wird eine neue, von der Primarstufe unabhängige Beurteilungsmappe ausgehändigt. Die Dokumentenmappe enthält alle Dokumente verpflichtende und optionale Dokumente. 

Die Dokumente, welche sich in der Dokumentenmappe  befinden, müssen während 15 Jahren archiviert und im Bedarfsfall griffbereit sein. Beurteuilungen sind im Kanton Bern besonders schützenswerte personenbezogene Daten, welche speziellen datenschützerischen Auflagen unterliegen.  Daher ist es sinnvoll, die Archivierung Profis zu überlassen. 

Aktuell gibt der Kanton Bern nicht vor, mit welchem Werkzeug die Dokumente erstellt und verwaltet werden müssen. Es ist den Schulen freigestellt, welches Werkzeug sie wählen. Viele Schulen im Kanton Bern setzen auf die offizielle Beurteilungsapplikation BU21, welche die BKD den Schulen kostenlos zur Verfügung stellt. 
Nutzt eine Schule das Angebot der BKD, gewährleistet die BKD in Zusammenarbeit mit einer Informatikfirma die Archivierung der Beurteilungsdokumente. Die Schule muss sich nicht selber darum kümmern. 

# Beurteilungsbericht (verpflichtend)

Der Beurteilungsbericht gibt Auskunft über die Beurteilungen in den einzelnen Fächern. Mit Ausnahme von Medien und Informatik sowie ERG muss die Beurteilung in Form einer Note erfolgen. Bei Medien und Informatik und ERG wird lediglich der Unterrichtsbesuch mit dem Vermerk "besucht" bestätigt. 

In den meisten Fällen wird die Note als simple Ziffer eingesetzt.
Bei Schülerinnen und Schülern mit individuellen Lernzielen (reduziert oder erweitert) wird die Ziffer mit einem * ergänzt. In diesem Fall muss zwingend das Formular zu den individuellen Lernzielen mit abgegeben und hinterlegt werden.

Nebst den Beurteilungen wird auf diesem Formular noch Folgendes deklariert: 

- Besuch Angebot der Schule (falls besucht)
- Besuch Unterricht HSK (falls besucht)
- Niveauzuteilung fürs neue Schuljahr
- Schullaufbahnentscheid
- Absenzen
- Angabe, ob das Standortgespräch stattgefunden hat

# Besonderes Volksschulangebot

Schülerinnen und Schüler im besonderen Volksschulangebot (individuell oder regelnah)

Schülerinnen und Schüler, welche das besondere Volksschulangebot (bVSAint) besuchen, erhalten spezielle Beurteilungsberichte. Dabei wird differenziert, ob die Schülerin/der Schüler den Unterricht individuell oder regelnah absolviert. 
Dementsprechend werden die Formulare ausgewählt.

### Regelnah:
Die Schülerin / der Schüler erhält einen fächerspezifischen Beurteilungsbericht analog zu den Regelschülerinnen und Regelschülern sowie einen ausführlichen Förderbericht.

### Individuell:
Schülerinnen und Schüler, welche das besondere Volksschulangebot mit indivuellem Pensum besuchen,  erhalten einen Beurteilungsbericht, welcher sich ausschliesslich auf die überfachlichen und personalen Kompetenzen bezieht. Zusätzlich wird ein Förderbericht ausgestellt. 

PDF

### Förderbericht: 
Der Förderbericht beinhaltet detaillierte Informationen zu fächerspezifischen Fortschritten und zu den personalen und überfachlichen Kompetenzen. 

# Portfolio zu personalen Kompetenzen und Schlüsselkompetenzen (verpflichtend)

Zusätzlich zu den fächerspezifischen Kompetenzen werden in der Beurteilung auch die überfachlichen, personalen Kompetenzen sowie die Schlüsselkompetenzen abgebildet. 
Dabei wird die Sicht der jeweiligen Schülerin/des jeweiligen Schülers ebenso abgebildet, wie die Sicht der Lehrpersonen. Hierzu füllen die Schülerinnen und Schüler einmal pro Jahr eine Selbstbeurteilung aus (zumeist auf Papier). Die Lehrperson überträgt die Angaben der Lernenden ins Portfolio (blaue Kästchen). Die Sicht der Lehrpersonen wird unter den an der Klasse unterrichtenden Lehrpersonen konsolidiert und in den roten Kästchen hinterlegt. 
Bemerkungen dürfen nur eingetragen werden, wenn sie der Schülerin/dem Schüler gegenüber wohlwollen formuliert sind und er Präzisierung dienen. 

PDF

# Protokoll zum Standortgespräch (verpflichtend)

Einmal jährlich wird den Eltern eine Einladung zu einem Standortgespräch zugestellt. Es steht den Eltern frei, ob sie die Möglichkeit wahrnehmen wollen oder nicht. Im Beurteilungsbericht wird festgehalten, ob ein Standortgespräch stattgefunden hat, oder ob es von den Eltern nicht gewünscht wurde. 

Findet ein Standortgespräch statt, bietet die Plattform BU21 die Möglichkeit, einen Leitfaden für das Gespräch anhand von möglichen Fragestellungen und Themen zu erstellen. 
In der Dokumentenmappe abgelegt wird am Ende das Protokoll zum Standortgespräch. In diesem werden stichwortartig die besprochenen Themen sowie in ausformulierter Form die Abmachungen und Vereinbarungen hinterlegt. 

Verzichten die Eltern auf das Standortgespräch, wird im Protokoll der Verzicht auf das Gespräch durch Ankreuzen des entsprechenden Feldes vermerkt. Das Formular wird ebenfalls visiert und als PDF zur Archivierung hochgeladen. 

Das Protokoll zum Standortgespräch wird den Eltern im Anschluss an das Gespräch (nicht erst zum Ende des Schuljahres) zur Unterschrift vorgelegt. Die visierte Version kann anschliessend als PDF-Upload zwecks Archivierung wiederum auf dem Portal BU21 hochgeladen werden. Das Original wird der Dokumentenmappe hinzugefügt. 

# Individueller Schullaufbahnentscheid (optional)

Die Schulleitung kann auf Antrag der Lehrpersonen für Schülerinnen und Schüler individuelle Schullaufbahnentscheide fällen. Diese werden unter dem laufenden Schuljahr mit den Eltern vereinbart. Ein individueller Schullaufbahnentscheid geht in der Regel aus einem Standortgespräch hervor. Der individuelle Schullaufbahnentscheid ist klar zu begründen. 

Ein individueller Schullaufbahnentscheid wird über das entsprechende Formular in der Dokumentenmappe dokumentiert. Die Eltern visieren das Formular und anschliessend wird dieses im PDF-Upload zur Archivierung hinterlegt.

Folgende Schullaufbahnentscheide können gefällt werden: 

PDF

* Niveauwechsel in einem Fach
* Wechsel des Schultyps
* Wiederholung einer Schuljahres
* Überspringen eines Schuljahres
* Zuweisung zu einer besonderen Klasse
* Rückführung in die Regelklasse

# Zusatzbericht bei individuellen Lernzielen (optional)

Schülerinnen und Schüler, welche nach individuellen reduzierten oder erweiterten Lernzielen unterrichtet werden, erhalten einen zusätzlichen Bericht, in welchem die individuellen Lernziele ersichtlich sind. Der Bericht kann unterschiedlich ausführlich sein.
Im Beurteilungsbericht sind die Beurteilungen der Fächer, in welchen nach individuellen Lernzielen gearbeitet wurde, mit einem * markiert. 
Der Zusatzbericht wird von der Fachlehrperson des entsprechenden Fachs oder der Lehrperson für die integrative Förderung erstellt. 

Da nur wenige Schülerinnen und Schüler nach individuellen Lernzielen unterrichtet werden, wird dieser Zusatzbericht realtiv selten benötigt.

PDF

# Tutorial zum Portal BU21

Im untenstehenden Video wird Ihnen gezeigt, wie das Portal BU21 aufgebaut ist, wie sie (summative) Beurteilungen erfassen und die Dokumente für die Dokumentenmappe erstellen und ausdrucken können. 
Eine ausführliche Hilfsdokumentation finden Sie direkt in der Applikation. 

VIDEO

# Dokumente anhand von Fallbeispielen erstellen

Lesen Sie die nachfolgenden Fallbeispiele und wählen Sie eines aus. Für die ausgewählte Schülerin oder den ausgewählten Schüler erstellen Sie in der Applikation BU21 eine vollständige Dokumentenmappe mit den untenstehenden Dokumenten: 

* Beurteilungsbericht des entsprechenden Schuljahres
* Portfolio mit personalen Kompetenzen und Schlüsselkompetenzen
* Individueller Schullaufbahnentscheid
* Protokoll zum Standortgespräch 

Beachten Sie die Angaben bei den einzelnen Schüler*innen und bilden Sie diese in der Beurteilungsmappe ab. Dennoch hat es bei allen Fallbeispielen auch genügend Interpretationsspielraum für eigene Eingaben.

Alle Klassen in den Fallbeispielen werden im Modell 4 unterrichtet. Die Stammklassen sind also niveaudurchmischt. Angaben zum besuchten Schultyp sind in den Grundeinstellungen der Schüler*in hinterlegt. Die Niveauzuteilung für das aktuelle und kommende Semester kann/muss durch dir Lehrperson beim jeweiligen Fach angepasst werden.

Musterlösungen zu den Fallbeispielen finden Sie am Schluss der jeweiligen Fallbeschreibung im aufklappbaren Fach. Die Lösungen sind als Beispiele zu verstehen. Es können abweichende Eingaben gemacht werden, da die Fallbeispiele genügend Interpretationsspielraum lassen.

# Fallbeispiel 1: Schülerin A

Schülerin A. ist eine Realschülerin. Die Leistungen liegen im genügenden bis guten Bereich. Sie hat ihre Stärken bei den MINT-Fächern. Deshalb konnte sie durch einen individuellen Schullaufbahnentscheid im Fach Mathematik ist sie dem Sekundarschulniveau zugeteilt werden. 

Schülerin A ist vielseitig interessiert, deshalb besucht sie auch zwei Angebote der Schule.

Sie ist gut organisiert und arbeitet selbstständig, jedoch hat sie teilweise Mühe, ihre Lernwege zu hinterfragen.

Schülerin A. ist eher eine Einzelgängerin. Sie arbeitet zielstrebig, aber am liebsten für sich alleine.

Wegen einem Fahrradunfall konnte sie den Unterricht mehrere Wochen nicht besuchen, konnte aber einige Inhalte mit digitalen Lernmodulen selber aufarbeiten.

Die Eltern unterstützen ihre Tochter gut – teilweise auch zu gut. Schülerin A. muss lernen, für sich selber einzustehen, damit ihr der Einstieg in die Berufswelt stressfrei gelingen kann.

## Musterlösung

PDFs

# Fallbeispiel 2: Schüler L

Schüler L. besucht den Unterricht als Sekundarschüler. Seine Leistungen sind (knapp genügend). Die Fremdsprachen fallen ihm schwer. Daher wurde ein individueller Schullaufbahnentscheid gefällt, so dass Schüler L. im Fach Französisch fortan dem Realschulniveau zugeteilt.

Für Schüler L. ist die Schule im Moment nicht so wichtig. Er interessiert sich eher für sein grosses Hobby, das Handballspielen. Er träumt von einer Karriere in der obersten Liga und investiert viel Zeit in das Training.

Durch den Sport ist L. ausgesprochen teamfähig. Wenn ihm etwas gefällt, ist er auch sehr motiviert. Gelingt etwas nicht auf Anhieb, verliert L. aber auch schnell die Geduld.

Zusammen mit den Eltern müssen nun Abmachungen getroffen werden, wie L. die Leistungen in der Schule stabilisieren und im besten Fall verbessern kann, und trotzdem Leistungssport betreiben kann.

## Lösung

PDFs

# Fallbeispiel 3: Schülerin M

Schülerin M. ist eine sehr gute Sekundarschülerin. Im Fach Deutsch ist sie dem speziellen Sekundarniveau zugeteilt. Schülerin M. ist sehr kreativ und im gestalterischen Bereich äusserst begabt. Schülerin M. möchte später das Gymnasium besuchen und hat viel Zeit ins Lernen investiert. Deshalb kann sie im Rahmen eines individuellen Schullaufbahnentscheids auch im Französisch das Niveau fortan im speziellen Sekundarschulniveau besuchen.

Das Lernen fällt ihr allgemein leicht, und sie hilft auch gerne ihren Mitschüler*innen. Nicht alle Jugendlichen der Klasse finden das immer toll – manchmal wird Schülerin M als Streberin taxiert, was ihr stark zu schaffen macht und sie auch oft daran hindert, ihren Standpunkt zu vertreten. Die Eltern wünschen sich daher eine Umteilung in eine andere Klasse. Dies muss thematisiert werden.

Da Schülerin M. eine gute Schullaufbahn wichtig ist, hat sie nur wenige Absenzen im Unterricht.

## Musterlösung

PDFs

# Fallbeispiel 4: Schüler S

Schüler S. ist ein Realschüler. Das Lernen fällt ihm schwer. Besonders in der Mathematik hat Schüler S. eine grosse Schwäche. Deshalb wird er im Fach Mathematik nach reduzierten individuellen Lernzielen unterrichtet und beurteilt.

Dennoch ist Schüler S. motiviert – er möchte seine Sache gut machen und sich verbessern. Deshalb besucht er das «Lernatelier», welches als Angebot der Schule freiwillig besucht werden kann. Er ist zuverlässig und pünktlich, jedoch lässt er sich viel zu schnell durch Mitschüler*innen oder Geschehnisse ablenken.

Die Eltern sind dankbar, dass die Schule S. die Möglichkeit bietet, in seinem Tempo zu lernen. Es wurde daher abgemacht, dass S. das Schuljahr wiederholen wird. Durch einen individuellen Schullaufbahnentscheid wurde dies während dem laufenden Schuljahr ermöglicht. 

## Musterlösung:

PDFs

