---
format: html
title: Nachteilsausgleich und individuelle Lernziele
authors:
  - Aline Löw
  - Daniel Ingrisani
  - Irene Althaus
citation: 
  author:
    - Aline Löw
    - Daniel Ingrisani
    - Irene Althaus
---
# Arbeitsauftrag und Fallbeispiel
Liebe Studierende

 Für die Bearbeitung des Lernmoduls gehen Sie nach den Schritten vor, die nachfolgend aufgeführt sind.
 
1. Schauen Sie sich den Screencast (Folienpräsentation mit Kommentar) und den Lernfilm zum Nachteilsausgleich an. Der Screencast wurde von meiner Kollegin Daniela Berger im Frühlingssemester 2020 erstellt. Die Inhalte sind weiterhin aktuell und geben Ihnen einen Überblick über die Thematik. Beachten Sie dabei bitte, dass im Kanton Bern im Gegensatz zu vielen anderen Kantonen der Schweiz in der Volksschule nicht der Begriff "Nachteilsausgleich" verwendet wird, sondern für dasselbe Konzept von "Ausgleichsmassnahmen" gesprochen wird (Link Abweichen von der DVBS). Für weiterführende Schulen/Mittelschulen und höhere Berufsschulen/Universität wird auch im Kanton Bern der Begriff "Nachteilsausgleich" verwendet (Link BKD).
2. Verschaffen Sie sich einen Überblick über die PDF's dieser Woche und lesen Sie in der Statistik der Sonderpädagogik vom Schuljahr 2018/19 das Kapitel 2.2 (S. 9-14). Schauen Sie sich im Anschluss daran die Ergebnisse des Forschungsprojekts von Sahli Lozano et al. an (siehe Folienpräsentation). Welche Übereinstimmungen erkennen Sie (z.B. Anteil SuS mit Migrationshintergrund, Geschlecht usw.)?
3. Überprüfen Sie ihr Wissen anhand der Fragen zum Lernmodul.
4. Überlegen Sie sich, was bezüglich der beiden Massnahmen (Nachteilsausgleich / iLZ) für Ihr Beurteilungskonzept wesentlich sein könnte.
5. Bearbeiten Sie anschliessend das Fallbeispiel (Text unten). Im Fallbeispiel steht, dass der Schüler Mario sowohl im Fach Deutsch, wie im Fach Mathematik reduzierte, individuelle Lernziele hat. Überlegen Sie, ob Sie diese Massnahme angemessen finden, oder ob es auch Argumente für eine andere Massnahme in einem der beiden Fächer gibt.
Falls Sie sich für die Massnahme Nachteilsausgleich oder Beurteilung ohne Note nach Art. 19 entscheiden, machen Sie sich auch Gedanken zu konkreten Massnahmen. Im Screencast auf der letzten Folie finden Sie dazu auch ein ausgefülltes Antragsformular mit Ideen.
Bei der Bearbeitung des Fallbeispiels können Sie ausgehen vom Fach, welches Sie studieren. Wenn Sie weder Mathematik noch Deutsch studieren, dann machen Sie sich Gedanken zu möglichen Massnahmen, um die Symptome des ADS auszugleichen.
6. Im Forum können Sie nach der Bearbeitung Fragen stellen, die ich (Barbara Rindlisbacher) beantworten werde.

### Fallbeispiel Mario            8. Klasse, Real
 
Angaben zur familiären Situation

* Familie: Mutter, Vater, zwei jüngere Brüder (13j. und 10j.)
* Schweizer Familie, mit drei Kindern, Hund und Katze, einem Haus auf dem Land – Mittelstand
* Eltern sind sehr um Mario bemüht und pflegen einen regen Austausch mit der Schule

 
Angaben zur Schullaufbahn

* riLZ (individuelle Lernziele) ab der 4. Klasse in Deutsch und Mathematik
* Bereits Auffälligkeiten auf der Unterstufe, jedoch liegen keine Dokumente dazu vor
* Grosse Schulunlust und Arbeitsverweigerung auf der Primarstufe – Mario verweigerte sich teilweise komplett

 
Angaben zur Problematik (unsystematische Beobachtungen zum Problemfeld)

* Mario fällt es schwer, sich auf den Unterricht zu konzentrieren
* Er hat Schwierigkeiten, Gelerntes abzurufen und mit neuen Inhalten zu verknüpfen
* Gemäss Aussagen der Eltern gibt es zuhause viel Streit, weil sich Mario verweigert und die Hausaufgaben nicht macht
* Im Unterricht zeigt er auffälliges und provozierendes Verhalten
* Er hat Schwierigkeiten beim Schreiben und im Leseverstehen
* Mario hat Schwierigkeiten in Mathematik

Zusammenfassung Lernstandserfassung Mathematik Anfang 8. Klasse

* M. löst viele Aufgaben richtig. Dezimalsystem, Proportionalität, Grössenvorstellungen und Mathematisieren sind vorhanden bzw. verstanden.
* Unsicherheiten zeigen sich bei der Beziehung Bruch – Dezimalbruch – Prozente. M. kennt einige Beziehungen, das Konzept scheint aber nicht wirklich verstanden.
* Rechnen mit Dezimalbrüchen ist fehleranfällig, insb. Subtraktion und Division.

 
Zusammenfassung Lese- und Schreibentwicklung

* M. liest Texte flüssig vor, jedoch zeigen sich Schwierigkeiten im Textverständnis (bereits kurze altersadäquate Texte werden nicht im Detail erfasst)
* M. hat Schwierigkeiten in der Textproduktion (Planung, Verschriftung, Überarbeitung) und in der Rechtschreibung. Die Verwendung des Computers ist motorisch für ihn schwierig.

Angaben zu bisher getroffenen Massnahmen (Abklärungen, Spezialunterricht, iLZ, ...)

* riLZ in den Fächern Mathematik und Deutsch
* Seit der Primarschule Heilpädagogische Unterstützung

 
Abklärungen zwischen Herbst und Frühling 7. Klasse bei

* SPD, Psychologin
* Neurologische Untersuchungen
* Logopädische Untersuchung

 
Resultate/Diagnosen:

* ADS
* schwere Sprachstörung (Grammatikverständnis, Schreibkompetenz, Wortschatz Dialekt – Hochdeutsch, Textverständnis)
* minimale spastische cerebrale Bewegungsstörung und Dyspraxie

 
NEU seit diesem Schuljahr drei zusätzliche GEF Lektionen (IF), 1 Lektion Logopädie
Dispensation vom Französischunterricht

# Input «Nachteilsausgleich & ILZ»

VIDEO PDF

# Lernfilm Nachteilsausgleich

VIDEO

# Ergebnisse zum Projekt SECABS

In dieser Folienpräsentation finden Sie Angaben zu den Projekten SECABS und CHARISMA, welche vom Institut für Forschung und Entwicklung an der PHBern unter der Leitung von Dr. C. Sahli Lozano durchgeführt wurden. Lesen Sie vor allem auf den beiden letzten Seiten die Ergebnisse zum Nachteilsausgleich auf der Sekundarstufe I.

VIDEO