---
format: html
title: Lernbegleitung und Lerncoaching
citation: 
  author:
    - Aline Löw
    - Daniel Ingrisani
    - Irene Althaus
---
# Allgemeine Informationen

Liebe Studierende

In diesem Lernmodul geht es um die «Lernbegleitung».

Arbeiten Sie das Lernmodul Schritt für Schritt durch.

Sollten Sie Fragen zum Thema haben, das Bedürfnis verspüren bestimmte Aspekte zu diskutieren oder wissen Sie nicht, wie Sie die behandelten Inhalte in Ihrem Beurteilungskonzept berücksichtigen sollen, dann ist es wichtig, dass Sie Ihre Anliegen an den dafür vorgesehenen Austauschterminen einbringen.

# Ziele des Lernmoduls

Die Studierenden ...

* kennen grundlegende Definitionen und Konzepte von Lernbegleitung.
* lernen Ideen kennen, zur individuellen Förderung und Unterstützung von Schüler*innen.
* können Lernende beim selbstständigen Lernen begleiten und motivieren. 
* verstehen, wie sie das Konzept des Cognitive Apprenticeship im Klassenraum umsetzen können. * kennen die Bedeutung von Feedback und wissen, was konstruktives Feedback beinhaltet.

# Lernbegleitung und Lerncoaching

Lernen Sie in diesem Input mehr über das Thema der Lernbegleitung.

VIDEO

# Cognitive Apprenticeship

Im Zusammenhang mit dem Thema der Lernbegleitung und speziell auch mit den verschiednene Phasen (Modeling, Coaching, Fading) möchten wir Ihnen den Ansatz des Cognitive Apprenticeship näherbringen.

Cognitive Apprenticeship ist ein Bildungsansatz, der die traditionelle Handwerkslehre in einen kognitiven, also geistigen Kontext überträgt. Dabei wird der Fokus auf das Erlernen von Denkprozessen und Problemlösungsstrategien durch Beobachtung und Anleitung eines erfahrenen Lehrers gelegt. Dieser Ansatz betont die Bedeutung von praktischen Übungen, die in authentischen Kontexten durchgeführt werden, und ermöglicht es den Lernenden, implizites Wissen durch explizite Lehrmethoden zu erwerben.

### Cognitive Apprenticeship: Überblick 

Cognitive Apprenticeship ist ein umfassender Ansatz, der die soziale Lerntheorie, strukturierte Unterrichtsmethoden und einen Schwerpunkt auf kontextuell sinnvolle Praxis kombiniert, um das Lernen und die Entwicklung von Fähigkeiten zu verbessern.
Der Ansatz basiert auf sozial-konstruktivistischen Ansätzen zur Anleitung.
Er betont authentische Aufgaben und Situationen sowie die Interaktionen zwischen erfahreneren und weniger erfahrenen Personen.
Der Ansatz zielt darauf ab, metakognitive Strategien und bereichsspezifische Problemlösungsfähigkeiten zu entwickeln. Dabei liegt der Fokus auf der Entwicklung kognitiver Fähigkeiten.

### Cognitive Apprenticeship - Konkret: Methoden

TEXTBILD

### Cognitive Apprenticeship: Theoretischer Hintergrund

Experten besitzen eine umfangreiche Menge an vernetztem Wissen und Strategien, deren Ausführung für Novizen oft mühelos erscheint. Traditioneller Schulunterricht isoliert Informationen oft von relevanten Kontexten, während kognitive Lehrlingsausbildungen den Fokus auf kontextuell eingebettete Praxis von Fähigkeiten legen, was für die Entwicklung von Expertise entscheidend ist. Die Rolle des Lehrers wechselt von einem Informationsanbieter zu einem Coach und Facilitator, der die Schüler in sinnvolle Problemlösungsaktivitäten einbindet.

Quellen:
Seel, N. (2012), Encyclopedia of the Sciences of Learning. Springer Science + Business Media. DOI 10.1007/978-1-4419-1428-6
Spielmann, D. (2017). E-Portfolio in der Schreibberatungsausbildung : Cognitive Apprenticeship und reflexive Praxis. wbv Publikation.
Tomsett, J. (2021). Collins et Al’s Cognitive Apprenticeship in Action. Melton, Suffolk: John Catt Educational.

# Feedback

Forschungen im Bereich der Pädagogik zeigen, dass Feedback von Lehrern eine wesentliche Rolle für das Lernen und Verständnis der Schüler spielt (Hattie, 2013 und Köller, 2012). Solche Rückmeldungen informieren die Schüler darüber, wo sie in ihrem Lernprozess stehen und weisen darauf hin, wie sie ihre Fähigkeiten ausbauen und ihre Leistungen verbessern können (Köller, 2012). Die Schüler erfahren dadurch Unterstützung und bekommen Raum, um eigene Gedanken zu entwickeln. Durch konstruktive und sachliche Rückmeldungen, sowohl mündlich als auch schriftlich, werden die Lern- und Denkprozesse der Schüler weiter gefördert. Diese Hilfestellungen können sich sowohl auf Inhalte als auch auf den Lernprozess beziehen. Solche unterstützenden Rückmeldungen ermöglichen es den Schülern, ihre Herangehensweise oder ihre Antworten zu überdenken (Kobarg & Seidel, 2007).

PDF VIDEO

# Peer-Feedback

Im folgenden Video "Austins's Butterfly: Models, Critique and Descriptive Feedback" sehen Sie eine Möglichkeit wie Peer-Feedback geübt werden kann. Schauen Sie sich den Film an und lösen Sie den Verarbeitungsauftrag unten.

VIDEO

## Verarbeitungsauftrag 

Beantworten Sie für sich die folgenden Fragen.

* Was gefällt Ihnen an dieser Methode?
* Was schätzen Sie an dieser Methode als eher kritisch ein?
* Inwiefern lässt sich diese Methode auf der Sekundarstufe I umsetzen?
* Wie würden Sie persönlich diese Methode oder auch nur Teile davon umsetzen?

Machen Sie sich Notizen zuhanden Ihres Beurteilungskonzepts.

# Verarbeitungsauftrag

Machen Sie sich nun zu den folgenden Reflexionsfragen Gedanken und notieren Sie wichtige Erkentnisse in Ihrem Beurteilungskonzept:

1. Welche Erfahrungen haben Sie mit Lernbegleitung (als Lehrperson oder als Lernende) bereits gemacht? Wie hat dies Ihre Einstellung zum Unterricht beeinflusst (z.B. in Bezug auf Lernstrategien, Motivation, etc.)?
2. Wie könnten Sie die Prinzipien des Cognitive Apprenticeship in Ihrer zukünftigen beruflichen Laufbahn anwenden und welche Vorteile erwarten Sie sich davon? Machen Sie ein konkretes Beispiel. 
3. Denken Sie an ein spezifisches Feedback, das Sie erhalten haben. Wie hat dieses Feedback Ihre Sichtweise auf Ihren eigenen Lernprozess verändert oder beeinflusst? Wie möchten Sie die Feedback-Kultur in Ihrem Unterricht umsetzen?