---
format: html
title: Organistarisches
citation: 
  author:
    - Aline Löw
    - Daniel Ingrisani
    - Irene Althaus
---

# Ziele und Intention

## Modulkompetenzen

Abgedeckte Indikatoren aus dem Modul «Formative Beurteilung»:

1.  Die Studierenden arbeiten mit den rechtlichen Vorgaben und den Empfehlungen zur formativen Beurteilung.
2.  Die Studierenden nutzen Verfahren, um den Lernbedarf im Hinblick auf fachspezi-fische, fachübergreifende, methodische und sprachliche Kompetenzen zu ermitteln.
3.  Die Studierenden verstehen einen Förderkreislauf und leiten Fördermassnahmen ab.

Abgedeckte Indikatoren aus dem Modul «Summative und prognostische Beurteilung»

1.  Die Studierenden arbeiten mit den rechtlichen Vorgaben und den Empfehlungen zur summativen und prognostischen Beurteilung.
2.  Die Studierenden nutzen Strategien, um mit dem Dilemma zwischen Förderung und Selektion umzugehen.
3.  Die Studierenden setzen ein Alignment zwischen Lernerwartungen, Lerninhalten und Leistungsbeurteilungen um.

## Intention des Seminars

Schüler\*innenbeurteilung und Schullaufbahnentscheide gehören zu den wichtigsten Tätigkeiten und Aufgaben der Lehrpersonen. Die Schulleitungen weisen darauf hin, dass Berufseinsteigende genau bei dieser Thematik manchmal in der Kritik von Erziehungsberechtigten stehen. Dies lässt sich vermeiden, wenn die Lehrpersonen von Anfang an mit einem differenzierten Beurteilungskonzept Transparenz schaffen. Differenziert meint, dass das «persönliche» Beurteilungskonzept die Umsetzung der übergeordneten Vorgaben (im Kanton Bern DVBS & AHB) im eigenen Unterricht aufzeigt. Lehrpersonen machen ihren Lernenden und den Erziehungsberechtigten damit transparent, wie sie die förderorientierte Beurteilung in den Unterricht integrieren (formative Beurteilung), wie überfachliche Kompetenzen beurteilt werden und wie die Noten und Prädikate in den Fachbereichen zustande kommen (summative Beurteilung).

# Teilnahmeregelung

Grundsätzlich wird die Teilnahme an den synchronen Veranstaltungen vor Ort erwartet. Dazu gehört selbstverständlich auch die aktive und intensive Auseinandersetzung mit den Inhalten und den eigenen Haltungen im Rahmen des asynchronen Selbststudiums.

Erhöhte Anforderungen an das Beurteilungskonzept und dafür keine Teilnahmekontrollen

Ich fühle mich dafür verantwortlich, dass Sie sich mit den Inhalten beschäftigen und sich diese aneignen und nicht, dass Sie Ihre Zeit in Veranstaltungsgefässen verbringen müssen. Deshalb werden verbindliche Anforderungen an die Qualität des Beurteilungskonzepts gestellt.

Das bedeutet, dass anhand eines Kriterienrasters Qualitätsansprüche an den Workload «Beurteilungskonzept» gestellt werden. Dieses Raster wird sowohl als Rückmeldungsinstrument, als auch zur Einschätzung der Qualität desselben verwendet. Es ist deshalb möglich, dass das Beurteilungskonzept «nicht erfüllt» sein kann. In diesem Falle dürfen Sie selbstverständlich das Konzept überarbeiten.

Verpflichtende Teilnahme an einem Coaching zum persönlichen Beurteilungskonzept

Wie Sie sicher bereits gesehen haben, gibt es Zeitgefässe, die ganz der individuellen Arbeit am Beurteilungskonzept gewidmet sind. Sie haben diese Zeit zur Verfügung, um das Konzept zu schreiben, aber auch, um ein formatives Feedback einzuholen. Dazu stehen Ihnen Zeitgefässe zur Verfügung, in denen Sie ein Coaching zu Ihrem Beurteilungskonzept erhalten können. Sie müssen bis zum Ende des Semesters mindestens einen Coachingtermin wahrgenommen haben, an dem ich Ihnen ein formatives Feedback auf Ihr Konzept geben kann.

# Workload «Beurteilungskonzept»

Am Ende des Semesters verfügen Sie über einen Entwurf eines persönlichen Beurteilungskonzepts, indem Sie an Ihren Vorkenntnissen anknüpfen und die wichtigsten Themen, Begriffe und Modelle aus dem Seminar (siehe Liste unten) in Ihre Argumentationen und Erläuterungen einbauen. Obwohl Ihre Argumentation persönlich ist, muss diese dennoch quellenbasiert erfolgen. Vergessen Sie also nicht, während des Verfassens des Konzepts konsequent und von Anfang an in Ihrem Lauftext die verwendeten Quellen anzugeben und sich allenfalls auch die Zitierweise von veranstaltunginternen Unterlagen anzueignen (siehe Vorschlag weiter unten). Sie entwickeln für Ihr Beurteilungskonzept eine eigene Struktur, welche Ihnen erlauben wird, alle künftigen Erfahrungen aus Unterricht und Praktika einzubauen.

Das Beurteilungskonzept ist Bestandteil des Workloads des Seminars und muss den Anforderungskriterien genügen, die in den Informationen zum Beurteilungskonzept einsehbar sind. Anhand dieser Kriterien erhalten Sie eine Rückmeldung sowie ein Prädikat. Es ist folglich möglich, dass das Beurteilungskonzept das Prädikat «nicht erfüllt» erhält.

Bei einem ungenügenden Beurteilungskonzept dürfen Sie dieses einmalig überarbeiten. Genügt dieses auch nach der Überarbeitung den Anforderungskriterien nicht, erfolgt ein Ausschluss aus der Veranstaltung.

Mit dem Beurteilungskonzept müssen folgende Themen, Begriffe und Modelle geklärt werden:

| Thema, Begriff, Modell                                                                                                                                                                                                                                                                                                                                           | Infos in den folgenden Lernmodulen                                            |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
| Summative Beurteilung bzw. selektionsorientierter Unterricht Leistungsbewertung                                                                                                                                                                                                                                                                                  | «Theoretische Grundlagen» «Gesamturteil & PSK» «Noten & Beurteilungsberichte» |
| Formative Beurteilung bzw. förderorientierter Unterricht Lernbegleitung                                                                                                                                                                                                                                                                                          | «Theoretische Grundlagen» «Förderorientierung»                                |
| Prognostische Beurteilung Schullaufbahnentscheide                                                                                                                                                                                                                                                                                                                | «Theoretische Grundlagen» «Niveaus & Schulmodelle»                            |
| Bezugsnormen der Bewertung (individuelle, soziale und kriteriale Bezugsnorm)                                                                                                                                                                                                                                                                                     | «Theoretische Grundlagen»                                                     |
| Beurteilungsgerechtigkeit (Leistungs-, Bedürfnis- und Gleichheitsprinzip)                                                                                                                                                                                                                                                                                        | «Theoretische Grundlagen»                                                     |
| Gesetzliche Grundlagen (LP21, AHB, DVBS)                                                                                                                                                                                                                                                                                                                         | «Gesetzliche Grundlagen»                                                      |
| Summative Beurteilungsgegenstände (im Kanton Bern Produkte, Lernkontrollen, Lernprozess)                                                                                                                                                                                                                                                                         | «Gesamturteil & PSK»                                                          |
| Notenfrage, Notengebung, Notenmassstäbe und Bewertungskriterien                                                                                                                                                                                                                                                                                                  | «Noten & Beurteilungsberichte» «Kompetenzorientierung»                        |
| Förderorientierung                                                                                                                                                                                                                                                                                                                                               | «Förderorientierung»                                                          |
| Lernbegleitung & Lerncoaching                                                                                                                                                                                                                                                                                                                                    | «Lernbegleitung & Lerncoaching»                                               |
| Gesamturteil (Zustandekommen der Gesamtnoten) & Beurteilungsbericht                                                                                                                                                                                                                                                                                              | «Gesamturteil & PSK»                                                          |
| Beurteilung der «Personalen Kompetenzen» sowie der «Schlüsselkompetenzen» (Portfolio)                                                                                                                                                                                                                                                                            | «Gesamturteil & PSK»                                                          |
| Klare Unterscheidung zwischen summativer Beurteilung des «Lernprozesses» mit den 5 überfachli-chen Aspekten (4 Beurteilungsbericht), der Beurteilung der «personalen Kompetenzen und Schlüs-selkompetenzen» (4 Portfolio) und der formativen Beurteilung der 56 überfachlichen (personalen, sozialen und methodischen) Kompetenzen im LP21 ( Standortgespräche). | «Gesamturteil & PSK»                                                          |
| Selbst- und Fremdbeurteilung                                                                                                                                                                                                                                                                                                                                     | «Gesetzliche Grundlagen»                                                      |
| Beurteilungsgrundsätze (z.B. FLUT) Förderorientierung (Lerncoaching & Feedback)                                                                                                                                                                                                                                                                                  | «Gesetzliche Grundlagen» «Förderorientierung»                                 |
| Sekundarstufenmodelle & Niveauunterricht                                                                                                                                                                                                                                                                                                                         | «Niveaus & Schulmodelle» Nachteilsausgleich & iLZ «Nachteilsausgleich & iLZ»  |

→ Weitere Informationen siehe Fach «Beurteilungskonzept» in der Spalte «Workloadaufträge».
