---
title: "Verstehensorientiert prüfen in Zeiten von KI"
subtitle: "Beurteilung Mathematik"
format: html
categories:
  - Formative Beurteilung
  - Summative und prognostische Beurteilung
  - Digitalität
authors:
    - name: Richard Conrardy
      orcid: 0009-0004-2063-6898
      id: 00383195
      email: richard.conrardy@phbern.ch
      url: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy
      affiliations:
        - name: University of Teacher Education Bern
          address: Länggassstrasse 35
          city: Bern
          postal-code: 3012
          url: https://www.phbern.ch
          department: Institut Sekundarstufe I
          ror: https://ror.org/05jf1ma54
    - name: Joël Adler
      url: https://www.phbern.ch/ueber-die-phbern/personen/joel-adler
      affiliations:
          - name: University of Teacher Education Bern
            address: Länggassstrasse 35
            city: Bern
            postal-code: 3012
            url: https://www.phbern.ch
            department: Institut Sekundarstufe I
            ror: https://ror.org/05jf1ma54
copyright: Dieser Kurs basiert auf dem Kurs von Peter Giger (https://pgigeruzh.github.io/informatik/) welcher unter einer  Creative Commons Attribution 4.0 International license (https://creativecommons.org/licenses/by/4.0/) steht.
---

::: {style="text-align: center;"}
[Organisationsblatt](https://phbern365.sharepoint.com/:x:/r/sites/IS1_Z_FachteamMathematik/Freigegebene%20Dokumente/General/Lerngelegenheiten/Beurteilung%20Mathematik%20Verstehensorientiert%20pr%C3%BCfen%20in%20Zeiten%20von%20KI/Studierende_Schreibrechte/Organisationsblatt%20Verstehensorientiert%20KI.xlsx?d=wf38b17f72e1f471bbdb882f9f7a981de&csf=1&web=1&e=6yfZvS){.knopf target="_blank"}

[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){.knopf .knopf-klein target="_blank"} [Materialraum](https://ilias.phbern.ch/goto_phbern_fold_2177856.html){.knopf .knopf-klein target="_blank"} [Porta-QT-Digitalität](https://porta.phbern.ch/content/page/62694b41dd910c2dedc2d1d1){.knopf .knopf-klein target="_blank"}
:::

# Wochenüberblick

| Woche | Thema                                        |                               Slides                               |                   Unterlagen                    |                                   Vorbereitung                                   |     |
|:---------:|:----------|:----------:|:---------:|:--------------:|-----------|
|   1   | Variablen und Conditionals                   | [<i class="bi bi-easel3-fill"></i>](woche_01.qmd){target="_blank"} |                                                 | [<i class="bi bi-file-earmark-check-fill"></i>](#vorbereitungsauftrag---woche-1) |     |
|   2   | Loops und Listen                             | [<i class="bi bi-easel3-fill"></i>](woche_02.qmd){target="_blank"} |                                                 |                                                                                  |     |
|   3   | Funktionen und Projektauftrag                | [<i class="bi bi-easel3-fill"></i>](woche_03.qmd){target="_blank"} |                                                 |                                                                                  |     |
|   4   | Projekt 1 (asynchron)                        |                                                                    | [<i class="bi bi-folder-fill"></i>](#projekt-1) |                                                                                  |     |
|   5   | Überschlagen üben und Sieb des Eratosthenes  |         [<i class="bi bi-easel3-fill"></i>](woche_05.qmd)          |                                                 |                                                                                  |     |
|   6   | Vier-Quadrate-Satz von Lagrange              |         [<i class="bi bi-easel3-fill"></i>](woche_06.qmd)          |                                                 |                                                                                  |     |
|   7   | Stammbrüche und Vermutung von Collatz        |         [<i class="bi bi-easel3-fill"></i>](woche_07.qmd)          |                                                 |                                                                                  |     |
|   8   | Brute force Gleichungen lösen & Kombinatorik |         [<i class="bi bi-easel3-fill"></i>](woche_08.qmd)          |                                                 |                                                                                  |     |
|   9   | Projekt 2 (asynchron)                        |                                                                    | [<i class="bi bi-folder-fill"></i>](#projekt-2) |                                                                                  |     |
|  10   | fällt im FS24 aus?                           |                                                                    |                                                 |                                                                                  |     |
|  11   | Algorithmen                                  |         [<i class="bi bi-easel3-fill"></i>](woche_10.qmd)          |                                                 |                                                                                  |     |
|  12   | Quarto                                       |         [<i class="bi bi-easel3-fill"></i>](woche_11.qmd)          |                                                 |                                                                                  |     |

: {.striped .hover .table-sm}

<hr>

# Wocheninhalte

## Vorbereitungsauftrag - Woche 1 {#vorbereitungsauftrag---woche-1}

Im Fokus der Lerngelegenheit steht das Programmieren. Installieren Sie **vor** der ersten Woche Rstudio und Python auf Ihrem Computer.

::: panel-tabset
## Windows 🪟

Grobe Installationsanleitung unter Windows:

1.  Installieren Sie R, [Webseite](https://cran.rstudio.com/bin/windows/base/).
2.  Installieren Sie RStudio, [Webseite](https://posit.co/download/rstudio-desktop/).
3.  Installieren Sie RTools, [Webseite](https://cran.r-project.org/bin/windows/Rtools/).
4.  In der *Console* in Rstudio: `install.packages("reticulate")`.
5.  In der *Console* in Rstudio: `reticulate::install_miniconda()`.

## MacOS 🍎

Grobe Installationsanleitung unter MacOS:

Öffnen Sie ein Terminal (Befehlszeile). Geben Sie folgende befehle ein:

1.  [Homebrew](https://brew.sh/) im *Terminal* installieren: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2.  [RStudio (+R)](https://formulae.brew.sh/cask/rstudio#default) im *Terminal* installieren: `brew install --cask rstudio`
3.  In der *Console* in Rstudio: `install.packages("reticulate")`.
4.  In der *Console* in Rstudio: `reticulate::install_miniconda()`.

Empfehlung: Installieren Sie Software grundsätzlich über [Homebrew](https://brew.sh/) (Paketmanager für MacOS).

Alle mit Homebrew installierten Programme können mit folgendem Terminalbefehl geupgradet werden: `brew update && brew upgrade && brew upgrade --cask && brew cleanup`

## GNU/Linux 🐧

Komm vorbei für einen gratis ☕️.

Installation hängt von der Distro ab.
:::

::: callout-note
Bei technischen Schwierigkeiten dürfen Sie sich gerne an Dozierende wenden. ChatGPT 3.5 liefert ebenfalls wertvolle Hilfestellungen zu Softwareproblemen.
:::

Überprüfen Sie Ihre Installation in dem Sie ein beliebiges Pythonprogramm ausführen, z.B.

``` python
print("Hello, World!")
```
---------------------------------

## Packages installieren (numpy)

Im `Terminal`folgenden Befehl eingeben: `pip install numpy`.
Falls Fehler gemeldet werden folgendes beachten:

1. Im `Terminal` folgendes eingeben: `pip --version``
2. In der Ausgabe den *path*, insb. Versionsnummer merken, z.B. `from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)` 
3. In Rstudio im Menü unter `Tools > Global Options` bei `Python` genau diesen Interpreter wählen und speichern.
4. Nun Library im `Terminal`mit `pip install numpy`installieren.


------------------------------------------------------------------------

## Projekt 1 {#projekt-1}

Entwickeln Sie Übungssituation im Kontext einer formativen oder summativen Beurteilung mit direktem Bezug zu den Indikatoren [MA.1.A.2.h](https://be.lehrplan.ch/101tLRW4xvunbRb5TfwTddzSsnKWUGRXA) oder [MA.1.A.2.i](https://be.lehrplan.ch/1017J6SBfwtVNTyD2VCwcbJdt6SD5mwXd). In dieser Übung müssen die Lernenden ein Computerprogramm erstellen oder ein von Ihnen erstelltes Programm anpassen und/oder benutzen.

Halten Sie schriftlich fest, wie diese Übung zur summativen Beurteilung beiträgt und gehen Sie dabei auf Chancen und Risiken von automatisierten Verfahren ein.

Sie können die Arbeit als Partnerarbeit erledigen.

------------------------------------------------------------------------

## Projekt 2 {#projekt-2}

Entwickeln Sie Übungssetting im Kontext einer formativen Beurteilung mit direktem Bezug zum Indikator [MA.3.B.2.e](https://be.lehrplan.ch/101qxA33rpuZHJ7LqqFSn39kpbUyt7DwW). In dieser Übung müssen die Lernenden ein Computerprogramm erstellen oder ein von Ihnen erstelltes Programm anpassen und/oder benutzen.

Halten Sie schriftlich fest:

-   wie diese Übung zur formativen Beurteilung beiträgt.
-   wie Sie mit diesem Übungssetting Unterrichtsmaterial und Medien zur Rückmeldung verwenden und auf eine konkrete Unterrichtssituation anpassen.
-   wie dieses Übungssetting die Entwicklung bildungssprachlicher Kompetenzen im Zusammenhang mit fachlichem Lernen fördert.

::: callout-tip
## Leistungsnachweis: Formative Beurteilung

Dieses Projekt kann integraler Bestandteil des Modulleistungsnachweises der formativen Beurteilung sein. Für offizielle Informationen zum Leistungsnachweis, lesen Sie die betreffende [Iliasseite](https://ilias.phbern.ch/goto_phbern_crs_1784163.html).
:::

# Aufgabenvorschläge
:::{.panel-tabset}
## Teilbarkeit

Bestimme alle natürlichen Zahlen kleiner als 100, die entweder durch 5 oder 7 teilbar sind. 

## Vierquadratesatz von Lagrange. 

* Bestimme alle natürlichen Zahlen kleiner als 100, die Summe von zwei Quadraten sind.

Man kann dann fragen, wie sich die Primzahlen, die Summe von zwei Quadraten sind, von den Primzahlen unterscheiden, die diese Eigenschaft nicht besitzen.

* Bestimme alle natürlichen Zahlen kleiner als 100, die Summe von drei Quadraten sind.
* Bestimme alle natürlichen Zahlen kleiner als 100, die Summe von drei Quadraten sind.
* Bestimme alle nat?rlichen Zahlen kleiner als 100, die Summe von vier Quadraten sind.

## Quadratzahlen

Die SuS erkennen, dass jede natürliche Zahl $n$ als Summe von vier Quadratzahlen dargestellt werden kann.

Nun könnte man die SuS auffordern, dasselbe Problem für Kubikzahlen zu untersuchen; also zu einer gegebenen Zahl $n$ für alle $s\leq n$, $s\in\mathbb{N}$, das kleinste $k$ mit  $s=\sum_{i=1}^kx_i^3$ zu bestimmen.

SuS, die schnell vorankommen, können die Frage der Darstellbarkeit natürlicher Zahlen als Summe vierter Potenzen untersuchen.

## Stammbrüche

Jeder Bruch $0<\frac{p}{q}<1$ kann als Summe verschiedener Stammbr?che dargestellt werden, zum Beispiel $\frac{4}{17}=\frac{1}{5}+\frac{1}{30}+\frac{1}{510}$.

Schreiben eines Programm, das bei Eingabe eines Bruchs $\frac{p}{q}$ eine Darstellung der Eingabe als Summe verschiedener (Folge streng fallender) Stammbrüche ausgibt. 

Man kann noch verlangen, dass die Eingabe $\frac{p}{q}$ auf die Bedingung $0<\frac{p}{q}<1$ getestet wird.

## Satz von Collatz

Nicht fehlen in dieser Liste darf die Folge bzw.~die Vermutung von Collatz: Für jede Startzahl $n$ erreicht man nach endlich vielen Schritten die Zahl 1, wenn man rekursiv $$a_0=n,\quad a_{n+1}=\begin{cases}\frac{a_n}{2} & a_n\text{ gerade }\\3a_n+1&a_n \text{ ungerade}\end{cases}$$


definiert. 

## Sieb des Eratosthenes

Das Sieb des Eratosthenes zur Bestimmung aller Primzahlen in einem vorgegebenen Anfangsabschnitt der natürlichen Zahlen.

Die Eingabe ist eine natürliche Zahl $n$, die Ausgabe die Liste aller Primzahlen kleiner gleich $n$.

Bestimmung aller Teiler (in einer Liste) einer natürlichen Zahl. Damit kann auch der grösste gemeinsame Teiler zweier Zahlen $a$ und $b$ (mit $a>b$) bestimmt werden, indem für die Elemente der Liste der Teiler von $b$ beginnend mit dem gr?ssten Element getestet wird, ob sie $a$ teilen. 

## Potenz-, Exponentialfunktion

Vergleich des Wachstums von Potenz- und Exponentialfunktionen. 

Ziel: Zur Eingabe zweier Zahlen $a$ und $b$, $a>1$, $b\in\mathbb{N}$,  die kleinste natürliche Zahl $n$ bestimmen, für die $n^b<a^n$ gilt. 

Die SuS erkennen, dass jede Exponentialfunktion (auch für $a=1.0001$) schneller wächst als jede Potenzfunktion.

## Nazistische Zahlen

Das Bestimmen aller narzistischer Zahlen kleiner einer gegebenen Zahl $n$

Eine Zahl heisst $k=a_{n-1}a_{n-2}\ldots a_1a_0$ *narzistisch*, wenn $k=\sum_{i=0}^{n-1}a_i^n$ gilt.

Beispiele narzistischer Zahlen sind 153 und 371 ($153=1^3+5^3+3^3$, $371=3^3+7^3+1^3$)


:::