---
title: "Verstehensorientiert prüfen in Zeiten von KI"
subtitle: "Beurteilung Mathematik"
format: html
categories:
  - Formative Beurteilung
  - Summative und prognostische Beurteilung
  - Digitalität
---

::: {style="text-align: center;"}
[Organisationsblatt](https://phbern365.sharepoint.com/:x:/r/sites/IS1_Z_FachteamMathematik/Freigegebene%20Dokumente/General/Lerngelegenheiten/Beurteilung%20Mathematik%20Verstehensorientiert%20pr%C3%BCfen%20in%20Zeiten%20von%20KI/Studierende_Schreibrechte/Organisationsblatt%20Verstehensorientiert%20KI.xlsx?d=wf38b17f72e1f471bbdb882f9f7a981de&csf=1&web=1&e=6yfZvS){.knopf target="_blank"}

[Porta-Mathematik](https://porta.phbern.ch/content/page/61fbb3277513396a43d9373a){.knopf .knopf-klein target="_blank"} [Materialraum](https://ilias.phbern.ch/goto_phbern_fold_2177856.html){.knopf .knopf-klein target="_blank"} [Porta-QT-Digitalität](https://porta.phbern.ch/content/page/62694b41dd910c2dedc2d1d1){.knopf .knopf-klein target="_blank"}
:::

# Wochenüberblick

| Woche | Thema                         |                               Slides                               |                  Unterlagen                   |                 Vorbereitung                  | Nachbereitung |
|:----------:|:-----------|:----------:|:----------:|:----------:|:----------:|
|   1   | Variablen und Conditionals    | [<i class="bi bi-easel3-fill"></i>](woche_01.qmd){target="_blank"} |       <i class="bi bi-folder-fill"></i>       | <i class="bi bi-file-earmark-check-fill"></i> |               |
|   2   | Loops und Listen              | [<i class="bi bi-easel3-fill"></i>](woche_02.qmd){target="_blank"} |       <i class="bi bi-folder-fill"></i>       |                                               |               |
|   3   | Funktionen und Projektauftrag | [<i class="bi bi-easel3-fill"></i>](woche_03.qmd){target="_blank"} |       <i class="bi bi-folder-fill"></i>       | <i class="bi bi-file-earmark-check-fill"></i> |               |
|   4   | Projektarbei (asynchron)      |                 <i class="bi bi-easel3-fill"></i>                  |       <i class="bi bi-folder-fill"></i>       |                                               |               |
|   5   | Algorithmen                   |                 <i class="bi bi-easel3-fill"></i>                  | [<i class="bi bi-folder-fill"></i>](#woche-8) |                                               |               |
|   6   | 1                             |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |
|   7   | 1                             |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |
|   8   | 1                             |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |
|   9   | 1                             |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |
|  10   | 1                             |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |
|  11   | Quarto                        |                 <i class="bi bi-easel3-fill"></i>                  |                                               |                                               |               |

: {.striped .hover .table-sm}

<hr>

# Wocheninhalte

## Vorbereitungsauftrag - Woche 1

Im Fokus der Lerngelegenheit steht das Programmieren. Dafür müssen gewisse Programm installiert und konfiguriert sein.

Installieren Sie **vor** der ersten Woche:

-   [Python](https://www.python.org/)
-   Entweder [RStudio](https://posit.co/products/open-source/rstudio/) oder [VSCode](https://code.visualstudio.com/)

Bei technischen Schwierigkeiten dürfen Sie sich gerne an den Dozierenden wenden.

## Vorbereitungsauftrag - Woche 3

------------------------------------------------------------------------

## Woche 8 {#woche-8}

#### {{< bi book >}} Inhalte

-   [{{< bi projector >}} Präsentationsfolien](woche_01.qmd){target="_blank"}
-   dsa

#### {{< bi journal-check >}}️ Auftrag

-   Bla
