---
format: 
  html: default
  pdf: default
  docx: default
title: Lernumgebungen
---

# Lernumgebung

## Definition

Lernumgebungen, gelegentlich auch Lernarrangement genannt, sind 

> Eine durch den Unterricht hergestellte Lernumgebung besteht aus einem Arrangement von Unterrichtsmethoden, Unterrichtstechniken, Lernmaterialien, Medien.
>
:::quelle
[@krapp_unterrichten_2010, S.615]
:::

> Unter Lernumgebung wird hier das Arrangement der äußeren Lernbedingungen (Personen und Institutionen, Geräte und Objekte, Symbole und Medien, Informationsmittel und Werkzeuge) und Instruktionsmaßnahmen (Lernaufgaben, Sequenz der Lernschritte, Methoden u. a.) verstanden, die Lernen ermöglichen und erleichtern. 
>
:::quelle
[@friedrich_analyse_1997, S.258]
:::

### Einschränkung

> “Hier stellt gerade die Grundschule umfassende Anforderungen an das Implementieren, die in den konfektioniert vorbereiteten Unterrichtsmaterialien nicht berücksichtigt sein können, sondern von dem Lehrenden spezifische Entscheidungen und Strukturierungen verlangen, die der konkreten Situation Rechnung tragen.”
>
:::quelle
[@wollring_kennzeichnung_2008, S.4]
:::

## Leitideen

> * Gegenstand und Sinn, Fach-Sinn und Werk-Sinn
> * Artikulation, Kommunikation, Soziale Organisation
> * Differenzieren
> * Logistik
> * Evaluation
> * Vernetzung mit anderen Lernumgebungen
>
:::quelle
[@wollring_kennzeichnung_2008, S.5]
:::

## Offen vs geschlossen

Falls Sie den Behaviourismus, Kognitivistismus und Konstruktivismus noch nicht kennen, lesen Sie  @krapp_unterrichten_2010, ab S.617. Die beiden ersten Positionen werden als "technologische Position" zusammengefasst.

### Leitfragen
Wie war ihr Unterricht gestaltet?

Welche Position haben vermutlich? https://fginfo.ksbg.ch/dokuwiki/lib/exe/fetch.php?media=lehrkraefte:blc:math-2021hw:funktionen-sv.pdf
Welche Position haben die Autoren des Mathbuchs?
Welche Position haben die Autoren von Mathematik (LMVZ)?

---

Learner centered, Knowledge centered, Assessment centered, community centered [@krapp_unterrichten_2010, S. 618]